syntax = "proto3";
package hmm;

option go_package = "github.com/zokwezo/sango/src/lib/hmm";

// Fields `from` and `to` are indexes into `states` or `tokens`a repeated field that depends on the containing field.
message FromToCount {
  int32  from  = 1;  // index into Model.states
	int32  to    = 2;  // index into Model.states (except Model.tokens for emission field)
	int64  count = 3;  // count
}

// Hidden Markov Model
message Model {
  // Deduplicated states found in the training corpus
  repeated string      states       = 1;

  // Deduplicated tokens found in the training corpus
  repeated string      tokens       = 2;

  // transition[iFrom].to[iTo]
	//   = count(states[iFrom](t) | states[iTo](t-1))
  // Map key is the index into `states` above.
  repeated FromToCount transitions  = 3;

  // emission[iFrom].to[iTo]
	//   = count(tokens[iTo](t) | states[iFrom](t))
  // Map key is the index into `states` above.
  repeated FromToCount emissions    = 4;

  // Total occurrences of each state
  // Map key is the index into `states` above.
	// The to field is not set.
  repeated FromToCount state_counts = 5;
  
  // Total unique (state, word) types in the training corpus
  int64                unique_pairs = 6;
}
