// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: hmm.proto

package hmm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Fields `from` and `to` are indexes into `states` or `tokens`a repeated field that depends on the containing field.
type FromToCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int32                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`   // index into Model.states
	To            int32                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`       // index into Model.states (except Model.tokens for emission field)
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"` // count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromToCount) Reset() {
	*x = FromToCount{}
	mi := &file_hmm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromToCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromToCount) ProtoMessage() {}

func (x *FromToCount) ProtoReflect() protoreflect.Message {
	mi := &file_hmm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromToCount.ProtoReflect.Descriptor instead.
func (*FromToCount) Descriptor() ([]byte, []int) {
	return file_hmm_proto_rawDescGZIP(), []int{0}
}

func (x *FromToCount) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *FromToCount) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *FromToCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Hidden Markov Model
type Model struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deduplicated states found in the training corpus
	States []string `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	// Deduplicated tokens found in the training corpus
	Tokens []string `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
	// transition[iFrom].to[iTo]
	//
	//	= count(states[iFrom](t) | states[iTo](t-1))
	//
	// Map key is the index into `states` above.
	Transitions []*FromToCount `protobuf:"bytes,3,rep,name=transitions,proto3" json:"transitions,omitempty"`
	// emission[iFrom].to[iTo]
	//
	//	= count(tokens[iTo](t) | states[iFrom](t))
	//
	// Map key is the index into `states` above.
	Emissions []*FromToCount `protobuf:"bytes,4,rep,name=emissions,proto3" json:"emissions,omitempty"`
	// Total occurrences of each state
	// Map key is the index into `states` above.
	// The to field is not set.
	StateCounts []*FromToCount `protobuf:"bytes,5,rep,name=state_counts,json=stateCounts,proto3" json:"state_counts,omitempty"`
	// Total unique (state, word) types in the training corpus
	UniquePairs   int64 `protobuf:"varint,6,opt,name=unique_pairs,json=uniquePairs,proto3" json:"unique_pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_hmm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_hmm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_hmm_proto_rawDescGZIP(), []int{1}
}

func (x *Model) GetStates() []string {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *Model) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *Model) GetTransitions() []*FromToCount {
	if x != nil {
		return x.Transitions
	}
	return nil
}

func (x *Model) GetEmissions() []*FromToCount {
	if x != nil {
		return x.Emissions
	}
	return nil
}

func (x *Model) GetStateCounts() []*FromToCount {
	if x != nil {
		return x.StateCounts
	}
	return nil
}

func (x *Model) GetUniquePairs() int64 {
	if x != nil {
		return x.UniquePairs
	}
	return 0
}

var File_hmm_proto protoreflect.FileDescriptor

const file_hmm_proto_rawDesc = "" +
	"\n" +
	"\thmm.proto\x12\x03hmm\"G\n" +
	"\vFromToCount\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x05R\x02to\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"\xf3\x01\n" +
	"\x05Model\x12\x16\n" +
	"\x06states\x18\x01 \x03(\tR\x06states\x12\x16\n" +
	"\x06tokens\x18\x02 \x03(\tR\x06tokens\x122\n" +
	"\vtransitions\x18\x03 \x03(\v2\x10.hmm.FromToCountR\vtransitions\x12.\n" +
	"\temissions\x18\x04 \x03(\v2\x10.hmm.FromToCountR\temissions\x123\n" +
	"\fstate_counts\x18\x05 \x03(\v2\x10.hmm.FromToCountR\vstateCounts\x12!\n" +
	"\funique_pairs\x18\x06 \x01(\x03R\vuniquePairsB&Z$github.com/zokwezo/sango/src/lib/hmmb\x06proto3"

var (
	file_hmm_proto_rawDescOnce sync.Once
	file_hmm_proto_rawDescData []byte
)

func file_hmm_proto_rawDescGZIP() []byte {
	file_hmm_proto_rawDescOnce.Do(func() {
		file_hmm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hmm_proto_rawDesc), len(file_hmm_proto_rawDesc)))
	})
	return file_hmm_proto_rawDescData
}

var file_hmm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hmm_proto_goTypes = []any{
	(*FromToCount)(nil), // 0: hmm.FromToCount
	(*Model)(nil),       // 1: hmm.Model
}
var file_hmm_proto_depIdxs = []int32{
	0, // 0: hmm.Model.transitions:type_name -> hmm.FromToCount
	0, // 1: hmm.Model.emissions:type_name -> hmm.FromToCount
	0, // 2: hmm.Model.state_counts:type_name -> hmm.FromToCount
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hmm_proto_init() }
func file_hmm_proto_init() {
	if File_hmm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hmm_proto_rawDesc), len(file_hmm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hmm_proto_goTypes,
		DependencyIndexes: file_hmm_proto_depIdxs,
		MessageInfos:      file_hmm_proto_msgTypes,
	}.Build()
	File_hmm_proto = out.File
	file_hmm_proto_goTypes = nil
	file_hmm_proto_depIdxs = nil
}
