#!/bin/bash
protoc --decode=hmm.SSECodes hmm.proto | awk '/^[a-zA-Z0-9_]+: [0-9]+/ {
    split($0, parts, ": ")
    if (parts[2] ~ /^[0-9]+$/ && parts[2] > 9) {
        printf "%s: 0x%X\n", parts[1], parts[2]
    } else {
        print $0
    }
} !/^[a-zA-Z0-9_]+: [0-9]+/ {print}'
