package transliterate

import (
	"bufio"
	"bytes"
	"regexp"
	"testing"
)

type TestCase struct {
	input       string
	matching    [][2]int
	nonmatching [][2]int
}

type Expect struct {
	re        *regexp.Regexp
	testCases []TestCase
}

func isEqual(lhs, rhs [][2]int) bool {
	if len(lhs) != len(rhs) {
		return false
	}
	for k, l := range lhs {
		if l[0] != rhs[k][0] || l[1] != rhs[k][1] {
			return false
		}
	}
	return true
}

func TestTokenize(t *testing.T) {
	expected := [...]Expect{
		Expect{regexp.MustCompile(`(?i)(?:[a-z]|[ß-ÿ])+`), []TestCase{
			{"", [][2]int{}, [][2]int{}},
			{"Ça3cÉj-ïq", [][2]int{{0, 3}, {4, 8}, {9, 12}}, [][2]int{{3, 4}, {8, 9}}},
		},
		},
	}
	for k, expect := range expected {
		for i, testCase := range expect.testCases {
			matching, nonmatching := tokenize(expect.re, testCase.input)
			if !isEqual(matching, testCase.matching) {
				t.Errorf("Expect[%v][%v].matching = %v but found %v\n", k, i, testCase.matching, matching)
			}
			if !isEqual(nonmatching, testCase.nonmatching) {
				t.Errorf("Expect[%v][%v].nonmatching = %v but found %v\n", k, i, testCase.nonmatching, nonmatching)
			}
		}
	}
}

type SangoInputOutput struct {
	Sango, Input, Output string
}

func TestEncodeInput(t *testing.T) {
	for k, r := range sangoInputOutput {
		var found bytes.Buffer
		if err := EncodeInput(bufio.NewWriter(&found), bufio.NewReader(bytes.NewBufferString(r.Sango))); err != nil {
			t.Errorf("Example %v: EncodeInput(%q) expected %q, returned error %v", k, r.Sango, r.Input, err)
		}
		if found.String() != r.Input {
			t.Errorf("Example %v: EncodeInput(%q) = %q, expected %q", k, r.Sango, found.String(), r.Input)
		}
	}
}

func TestEncodeOutput(t *testing.T) {
	for k, r := range sangoInputOutput {
		var found bytes.Buffer
		if err := EncodeOutput(bufio.NewWriter(&found), bufio.NewReader(bytes.NewBufferString(r.Sango))); err != nil {
			t.Errorf("Example %v: EncodeOutput(%q) expected %q, returned error %v", k, r.Sango, r.Output, err)
		}
		if found.String() != r.Output {
			t.Errorf("Example %v: EncodeOutput(%q) = %q, expected %q", k, r.Sango, found.String(), r.Output)
		}
	}
}

func TestDecodeInput(t *testing.T) {
	for k, r := range sangoInputOutput {
		var found bytes.Buffer
		if err := DecodeInput(bufio.NewWriter(&found), bufio.NewReader(bytes.NewBufferString(r.Input))); err != nil {
			t.Errorf("Example %v: DecodeInput(%q) expected %q, returned error %v", k, r.Input, r.Sango, err)
		}
		if found.String() != r.Sango {
			t.Errorf("Example %v: DecodeInput(%q) = %q, expected %q", k, r.Input, found.String(), r.Sango)
		}
	}
}

func TestDecodeOutput(t *testing.T) {
	for k, r := range sangoInputOutput {
		var found bytes.Buffer
		if err := DecodeOutput(bufio.NewWriter(&found), bufio.NewReader(bytes.NewBufferString(r.Output))); err != nil {
			t.Errorf("Example %v: DecodeOutput(%q) expected %q, returned error %v", k, r.Output, r.Sango, err)
		}
		if found.String() != r.Sango {
			t.Errorf("Example %v: DecodeOutput(%q) = %q, expected %q", k, r.Output, found.String(), r.Sango)
		}
	}
}

var sangoInputOutput = [...]SangoInputOutput{
	{"a", "a", "a"},
	{"â", "Ja", "A"},
	{"â", "Ja", "A"},
	{"nga", "nga", "nga"},
	{"ngbi", "ngbi", "ngbi"},
	{"ngɔ̈", "ngjc", "ngC"},
	{"ababâa", "ababJaa", "abaBAa"},
	{"âdɛ", "Jadx", "Adx"},
	{"âdu", "Jadu", "Adu"},
	{"âe", "Jae", "Ae"},
	{"Afrîka", "qafrJika", "qaFRIka"},
	{"ahɔ̈n", "ahjcn", "ahCN"},
	{"ahɔ̈n kûɛ̂", "ahjcn kJuJx", "ahCN KUX"},
	{"ahɔ̈n ndɔ̈nî", "ahjcn ndjcnJi", "ahCN ndCNI"},
	{"âi", "Jai", "Ai"},
	{"âkötarä", "Jakjotarja", "AkOtarA"},
	{"âla", "Jala", "Ala"},
	{"alamëti", "alamjeti", "alamEti"},
	{"âla mvɛnî", "Jala mvxnJi", "Ala mvxNI"},
	{"alë", "alje", "alE"},
	{"alëbɛdê", "aljebxdJe", "alEbxDE"},
	{"alë-zo", "alje-zo", "alE-zo"},
	{"alimëti", "alimjeti", "alimEti"},
	{"alimëti", "alimjeti", "alimEti"},
	{"âmbeso", "Jambeso", "Ambeso"},
	{"ambïi", "ambjii", "ambIi"},
	{"Amerîka", "qamerJika", "qameRIka"},
	{"ânarûmbatêe", "JanarJumbatJee", "AnaRUmbaTEe"},
	{"andâa", "andJaa", "aNDAa"},
	{"ândɛ", "Jandx", "Andx"},
	{"ândö", "Jandjo", "AndO"},
	{"ânge", "Jange", "Ange"},
	{"Angɛlêe", "qangxlJee", "qangxLEe"},
	{"angɔ̈rɔ", "angjcrc", "angCrc"},
	{"angɔ̈rɔ", "angjcrc", "angCrc"},
	{"ânî", "JanJi", "ANI"},
	{"ânï", "Janji", "AnI"},
	{"aparandëe", "aparandjee", "aparandEe"},
	{"aparandëe", "aparandjee", "aparandEe"},
	{"äpɛ", "japx", "jApx"},
	{"ara", "ara", "ara"},
	{"arâbu", "arJabu", "aRAbu"},
	{"arara", "arara", "arara"},
	{"asa", "asa", "asa"},
	{"asî na", "asJi na", "aSI na"},
	{"asî na ... awe", "asJi na ... awe", "aSI na ... awe"},
	{"asî ngâ na", "asJi ngJa na", "aSI NGA na"},
	{"âta", "Jata", "Ata"},
	{"atâa", "atJaa", "aTAa"},
	{"atâa sô", "atJaa sJo", "aTAa SO"},
	{"aû", "aJu", "aU"},
	{"awâne", "awJane", "aWAne"},
	{"awɛ", "awx", "awx"},
	{"âyi", "Jayi", "Ayi"},
	{"ba", "ba", "ba"},
	{"bâ", "bJa", "BA"},
	{"bä", "bja", "bA"},
	{"bä", "bja", "bA"},
	{"bâa", "bJaa", "BAa"},
	{"bâa mo tɛnɛ", "bJaa mo txnx", "BAa mo txnx"},
	{"bâanga", "bJaanga", "BAanga"},
	{"bâa yä", "bJaa yja", "BAa yA"},
	{"baba", "baba", "baba"},
	{"babâ", "babJa", "baBA"},
	{"bâbâ", "bJabJa", "BABA"},
	{"babâla", "babJala", "baBAla"},
	{"babango", "babango", "babango"},
	{"bäbɔlɔ", "bjabclc", "bAbclc"},
	{"bäbɔrɔ", "bjabcrc", "bAbcrc"},
	{"badâ", "badJa", "baDA"},
	{"bâda", "bJada", "BAda"},
	{"bâdabûku", "bJadabJuku", "BAdaBUku"},
	{"bâdahalëzo", "bJadahaljezo", "BAdahalEzo"},
	{"bâgara", "bJagara", "BAgara"},
	{"bagbara", "bagbara", "bagbara"},
	{"bâge", "bJage", "BAge"},
	{"bâ-hülë", "bJa-hjulje", "BA-hUlE"},
	{"bakalê", "bakalJe", "bakaLE"},
	{"bakarî", "bakarJi", "bakaRI"},
	{"bâke", "bJake", "BAke"},
	{"bâke", "bJake", "BAke"},
	{"bäkɔngɔ̈", "bjakcngjc", "bAkcngC"},
	{"bäkoyä", "bjakoyja", "bAkoyA"},
	{"bäkpä", "bjakpja", "bAkpA"},
	{"bäkürü", "bjakjurju", "bAkUrU"},
	{"bakûtu", "bakJutu", "baKUtu"},
	{"bala", "bala", "bala"},
	{"bala", "bala", "bala"},
	{"balabâla", "balabJala", "balaBAla"},
	{"balaka", "balaka", "balaka"},
	{"balama", "balama", "balama"},
	{"balambo", "balambo", "balambo"},
	{"balangɛ̈ti", "balangjxti", "balangXti"},
	{"balaɔ̈", "balajc", "balajC"},
	{"balapâa", "balapJaa", "balaPAa"},
	{"bâlâwâ", "bJalJawJa", "BALAWA"},
	{"bale", "bale", "bale"},
	{"balë", "balje", "balE"},
	{"balë", "balje", "balE"},
	{"balêe", "balJee", "baLEe"},
	{"balëe", "baljee", "balEe"},
	{"balë-mbârâmbârâ", "balje-mbJarJambJarJa", "balE-MBARAMBARA"},
	{"balë-mbârâmbârâ", "balje-mbJarJambJarJa", "balE-MBARAMBARA"},
	{"balëmbârâmbârâ", "baljembJarJambJarJa", "balEMBARAMBARA"},
	{"balëmbârâmbârâ", "baljembJarJambJarJa", "balEMBARAMBARA"},
	{"balë-mbâsâmbârâ", "balje-mbJasJambJarJa", "balE-MBASAMBARA"},
	{"balë-mbâsâmbârâ", "balje-mbJasJambJarJa", "balE-MBASAMBARA"},
	{"balëmbâsâmbârâ", "baljembJasJambJarJa", "balEMBASAMBARA"},
	{"balëmbâsâmbârâ", "baljembJasJambJarJa", "balEMBASAMBARA"},
	{"balë-miɔmbe", "balje-micmbe", "balE-micmbe"},
	{"balë-miɔmbe", "balje-micmbe", "balE-micmbe"},
	{"balëmiɔmbe", "baljemicmbe", "balEmicmbe"},
	{"balëmiɔmbe", "baljemicmbe", "balEmicmbe"},
	{"balë-ngümbâyä", "balje-ngjumbJayja", "balE-ngUMBAyA"},
	{"balë-ngümbâyä", "balje-ngjumbJayja", "balE-ngUMBAyA"},
	{"balëngümbâyä", "baljengjumbJayja", "balEngUMBAyA"},
	{"balëngümbâyä", "baljengjumbJayja", "balEngUMBAyA"},
	{"balë-ɔ̂kɔ", "balje-Jckc", "balE-Ckc"},
	{"balë-ɔ̂kɔ", "balje-Jckc", "balE-Ckc"},
	{"balëɔ̈kɔ", "baljejckc", "balEjCkc"},
	{"balëɔ̈kɔ", "baljejckc", "balEjCkc"},
	{"balë-ɔ̂kɔ na mbârâmbârâ", "balje-Jckc na mbJarJambJarJa", "balE-Ckc na MBARAMBARA"},
	{"balë-ɔ̂kɔ na mbârâmbârâ", "balje-Jckc na mbJarJambJarJa", "balE-Ckc na MBARAMBARA"},
	{"balëɔ̈kɔ na mbârâmbârâ", "baljejckc na mbJarJambJarJa", "balEjCkc na MBARAMBARA"},
	{"balëɔ̈kɔ na mbârâmbârâ", "baljejckc na mbJarJambJarJa", "balEjCkc na MBARAMBARA"},
	{"balë-ɔ̂kɔ na mbâsâmbârâ", "balje-Jckc na mbJasJambJarJa", "balE-Ckc na MBASAMBARA"},
	{"balë-ɔ̂kɔ na mbâsâmbârâ", "balje-Jckc na mbJasJambJarJa", "balE-Ckc na MBASAMBARA"},
	{"balëɔ̈kɔ na mbâsâmbârâ", "baljejckc na mbJasJambJarJa", "balEjCkc na MBASAMBARA"},
	{"balëɔ̈kɔ na mbâsâmbârâ", "baljejckc na mbJasJambJarJa", "balEjCkc na MBASAMBARA"},
	{"balë-ɔ̂kɔ na miambe", "balje-Jckc na miambe", "balE-Ckc na miambe"},
	{"balë-ɔ̂kɔ na miambe", "balje-Jckc na miambe", "balE-Ckc na miambe"},
	{"balëɔ̈kɔ na miambe", "baljejckc na miambe", "balEjCkc na miambe"},
	{"balëɔ̈kɔ na miambe", "baljejckc na miambe", "balEjCkc na miambe"},
	{"balë-ɔ̂kɔ na miɔmbe", "balje-Jckc na micmbe", "balE-Ckc na micmbe"},
	{"balë-ɔ̂kɔ na miɔmbe", "balje-Jckc na micmbe", "balE-Ckc na micmbe"},
	{"balëɔ̈kɔ na miɔmbe", "baljejckc na micmbe", "balEjCkc na micmbe"},
	{"balëɔ̈kɔ na miɔmbe", "baljejckc na micmbe", "balEjCkc na micmbe"},
	{"balë-ɔ̂kɔ na ngümbâyä", "balje-Jckc na ngjumbJayja", "balE-Ckc na ngUMBAyA"},
	{"balë-ɔ̂kɔ na ngümbâyä", "balje-Jckc na ngjumbJayja", "balE-Ckc na ngUMBAyA"},
	{"balëɔ̈kɔ na ngümbâyä", "baljejckc na ngjumbJayja", "balEjCkc na ngUMBAyA"},
	{"balëɔ̈kɔ na ngümbâyä", "baljejckc na ngjumbJayja", "balEjCkc na ngUMBAyA"},
	{"balë-ɔ̂kɔ na ɔkü", "balje-Jckc na ckju", "balE-Ckc na ckU"},
	{"balë-ɔ̂kɔ na ɔkü", "balje-Jckc na ckju", "balE-Ckc na ckU"},
	{"balëɔ̈kɔ na ɔkü", "baljejckc na ckju", "balEjCkc na ckU"},
	{"balëɔ̈kɔ na ɔkü", "baljejckc na ckju", "balEjCkc na ckU"},
	{"balë-ɔ̂kɔ na omɛnë", "balje-Jckc na omxnje", "balE-Ckc na omxnE"},
	{"balë-ɔ̂kɔ na omɛnë", "balje-Jckc na omxnje", "balE-Ckc na omxnE"},
	{"balëɔ̈kɔ na omɛnë", "baljejckc na omxnje", "balEjCkc na omxnE"},
	{"balëɔ̈kɔ na omɛnë", "baljejckc na omxnje", "balEjCkc na omxnE"},
	{"balë-ɔ̂kɔ na otâ", "balje-Jckc na otJa", "balE-Ckc na oTA"},
	{"balë-ɔ̂kɔ na otâ", "balje-Jckc na otJa", "balE-Ckc na oTA"},
	{"balëɔ̈kɔ na otâ", "baljejckc na otJa", "balEjCkc na oTA"},
	{"balëɔ̈kɔ na otâ", "baljejckc na otJa", "balEjCkc na oTA"},
	{"balë-ɔ̂kɔ na ûse", "balje-Jckc na Juse", "balE-Ckc na Use"},
	{"balë-ɔ̂kɔ na ûse", "balje-Jckc na Juse", "balE-Ckc na Use"},
	{"balëɔ̈kɔ na ûse", "baljejckc na Juse", "balEjCkc na Use"},
	{"balëɔ̈kɔ na ûse", "baljejckc na Juse", "balEjCkc na Use"},
	{"balë-ɔ̂kɔ na usïö", "balje-Jckc na usjijo", "balE-Ckc na usIjO"},
	{"balë-ɔ̂kɔ na usïö", "balje-Jckc na usjijo", "balE-Ckc na usIjO"},
	{"balëɔ̈kɔ na usïö", "baljejckc na usjijo", "balEjCkc na usIjO"},
	{"balëɔ̈kɔ na usïö", "baljejckc na usjijo", "balEjCkc na usIjO"},
	{"balë-ɔkü", "balje-ckju", "balE-ckU"},
	{"balë-ɔkü", "balje-ckju", "balE-ckU"},
	{"balëɔkü", "baljeckju", "balEckU"},
	{"balëɔkü", "baljeckju", "balEckU"},
	{"balë-omɛnë", "balje-omxnje", "balE-omxnE"},
	{"balë-omɛnë", "balje-omxnje", "balE-omxnE"},
	{"balëomɛnë", "baljeomxnje", "balEomxnE"},
	{"balëomɛnë", "baljeomxnje", "balEomxnE"},
	{"balë-otâ", "balje-otJa", "balE-oTA"},
	{"balë-otâ", "balje-otJa", "balE-oTA"},
	{"balëotâ", "baljeotJa", "balEoTA"},
	{"balëotâ", "baljeotJa", "balEoTA"},
	{"balë-ûse", "balje-Juse", "balE-Use"},
	{"balë-ûse", "balje-Juse", "balE-Use"},
	{"balë-ûse", "balje-Juse", "balE-Use"},
	{"balë-ûse", "balje-Juse", "balE-Use"},
	{"balëusïö", "baljeusjijo", "balEusIjO"},
	{"balëusïö", "baljeusjijo", "balEusIjO"},
	{"balëusïö", "baljeusjijo", "balEusIjO"},
	{"balëusïö", "baljeusjijo", "balEusIjO"},
	{"bämarä", "bjamarja", "bAmarA"},
	{"bambî", "bambJi", "baMBI"},
	{"bambinga", "bambinga", "bambinga"},
	{"baminga", "baminga", "baminga"},
	{"bambü", "bambju", "bambU"},
	{"bandeko", "bandeko", "bandeko"},
	{"bândembö", "bJandembjo", "BAndembO"},
	{"bandö", "bandjo", "bandO"},
	{"banga", "banga", "banga"},
	{"bânga", "bJanga", "BAnga"},
	{"bängâ", "bjangJa", "bANGA"},
	{"bângbi", "bJangbi", "BAngbi"},
	{"bângbi", "bJangbi", "BAngbi"},
	{"bangi", "bangi", "bangi"},
	{"bangî", "bangJi", "baNGI"},
	{"bângi", "bJangi", "BAngi"},
	{"bâ-ngû", "bJa-ngJu", "BA-NGU"},
	{"bäö", "bjajo", "bAjO"},
	{"bara", "bara", "bara"},
	{"bara", "bara", "bara"},
	{"barama", "barama", "barama"},
	{"baramïi", "baramjii", "baramIi"},
	{"barao", "barao", "barao"},
	{"baraö", "barajo", "barajO"},
	{"basɛ̈nzi", "basjxnzi", "basXnzi"},
	{"bata", "bata", "bata"},
	{"batöo", "batjoo", "batOo"},
	{"batöo", "batjoo", "batOo"},
	{"bâ-wërë", "bJa-wjerje", "BA-wErE"},
	{"bâyâ", "bJayJa", "BAYA"},
	{"bazïngêre", "bazjingJere", "bazINGEre"},
	{"bë", "bje", "bE"},
	{"bɛ", "bx", "bx"},
	{"bɛ̂", "bJx", "BX"},
	{"bɛ̂", "bJx", "BX"},
	{"bɛ̂-afrîka", "bJx-afrJika", "BX-aFRIka"},
	{"bebëe", "bebjee", "bebEe"},
	{"bebëe", "bebjee", "bebEe"},
	{"bɛ̂-bï", "bJx-bji", "BX-bI"},
	{"bekâni", "bekJani", "beKAni"},
	{"bekâni", "bekJani", "beKAni"},
	{"bɛ̂-kɔ̈dɔ̈rɔ̈", "bJx-kjcdjcrjc", "BX-kCdCrC"},
	{"bɛ̂-kɔ̈mbïtɛ", "bJx-kjcmbjitx", "BX-kCmbItx"},
	{"bëkpä", "bjekpja", "bEkpA"},
	{"bɛ̂-lâ", "bJx-lJa", "BX-LA"},
	{"bɛ̂lâawü", "bJxlJaawju", "BXLAawU"},
	{"bele", "bele", "bele"},
	{"bɛlɛ", "bxlx", "bxlx"},
	{"bɛ̂lɛ", "bJxlx", "BXlx"},
	{"belü", "belju", "belU"},
	{"bema", "bema", "bema"},
	{"bɛnda", "bxnda", "bxnda"},
	{"bɛ̂-ndâmbo", "bJx-ndJambo", "BX-NDAmbo"},
	{"bengbä", "bengbja", "bengbA"},
	{"bengbä-bengbä", "bengbja-bengbja", "bengbA-bengbA"},
	{"bengbä-kɛ̂tɛ̂", "bengbja-kJxtJx", "bengbA-KXTX"},
	{"bɛ̈ngɛ̈", "bjxngjx", "bXngX"},
	{"bɛ̈ngɔ̈", "bjxngjc", "bXngC"},
	{"bɛ̈ngɔ̈", "bjxngjc", "bXngC"},
	{"bɛ̂-nyämä", "bJx-nyjamja", "BX-nyAmA"},
	{"bere", "bere", "bere"},
	{"berë", "berje", "berE"},
	{"bɛrɛ", "bxrx", "bxrx"},
	{"bɛ̂rɛ", "bJxrx", "BXrx"},
	{"berebere", "berebere", "berebere"},
	{"bɛrɛdɛ̈lɛ", "bxrxdjxlx", "bxrxdXlx"},
	{"bɛrɛdɛ̈lɛ", "bxrxdjxlx", "bxrxdXlx"},
	{"bëtä", "bjetja", "bEtA"},
	{"bɛ̂tâ", "bJxtJa", "BXTA"},
	{"bɛ̂-zöngö", "bJx-zjongjo", "BX-zOngO"},
	{"bi", "bi", "bi"},
	{"bî", "bJi", "BI"},
	{"bï", "bji", "bI"},
	{"bï", "bji", "bI"},
	{"bîâ", "bJiJa", "BIA"},
	{"bîakü", "bJiakju", "BIakU"},
	{"bîângâ", "bJiJangJa", "BIANGA"},
	{"bîanî", "bJianJi", "BIaNI"},
	{"bi bɛ̂", "bi bJx", "bi BX"},
	{"bi-bɛ̂", "bi-bJx", "bi-BX"},
	{"bibila", "bibila", "bibila"},
	{"bibila", "bibila", "bibila"},
	{"bîɛ̂lɛ", "bJiJxlx", "BIXlx"},
	{"bïkua", "bjikua", "bIkua"},
	{"bïkua-ɔ̂kɔ", "bjikua-Jckc", "bIkua-Ckc"},
	{"bïkua-ɔkü", "bjikua-ckju", "bIkua-ckU"},
	{"bïkua-otâ", "bjikua-otJa", "bIkua-oTA"},
	{"bïkua-ûse", "bjikua-Juse", "bIkua-Use"},
	{"bïkua-usïö", "bjikua-usjijo", "bIkua-usIjO"},
	{"bilarzïi", "bilarzjii", "bilarzIi"},
	{"bîlîbili", "bJilJibili", "BILIbili"},
	{"bi na bɛ̂", "bi na bJx", "bi na BX"},
	{"bindi", "bindi", "bindi"},
	{"bindî", "bindJi", "biNDI"},
	{"bînga", "bJinga", "BInga"},
	{"bingbi", "bingbi", "bingbi"},
	{"bingbi", "bingbi", "bingbi"},
	{"bingbi tɛrɛ̂", "bingbi txrJx", "bingbi txRX"},
	{"biö", "bijo", "bijO"},
	{"bi patärä", "bi patjarja", "bi patArA"},
	{"birâ", "birJa", "biRA"},
	{"bîrï", "bJirji", "BIrI"},
	{"bîrîbiri", "bJirJibiri", "BIRIbiri"},
	{"birîki", "birJiki", "biRIki"},
	{"biritâni", "biritJani", "biriTAni"},
	{"biröo", "birjoo", "birOo"},
	{"bisêe", "bisJee", "biSEe"},
	{"biyëe", "biyjee", "biyEe"},
	{"bô", "bJo", "BO"},
	{"bö", "bjo", "bO"},
	{"bobo", "bobo", "bobo"},
	{"bôi", "bJoi", "BOi"},
	{"bôingû", "bJoingJu", "BOiNGU"},
	{"bɔlɛ", "bclx", "bclx"},
	{"bolingo", "bolingo", "bolingo"},
	{"boma", "boma", "boma"},
	{"bôndo", "bJondo", "BOndo"},
	{"böndö", "bjondjo", "bOndO"},
	{"bɔngɔ̂", "bcngJc", "bcNGC"},
	{"bɔngɔ̈", "bcngjc", "bcngC"},
	{"bôon", "bJoon", "BOoN"},
	{"bôrö", "bJorjo", "BOrO"},
	{"börö", "bjorjo", "bOrO"},
	{"bɔrɔ", "bcrc", "bcrc"},
	{"bɔ̂sɔ", "bJcsc", "BCsc"},
	{"bɔ̂sɔngbi", "bJcscngbi", "BCscngbi"},
	{"bɔ̂sɔngbi", "bJcscngbi", "BCscngbi"},
	{"bɔ̂sɔngbi tɛrɛ̂", "bJcscngbi txrJx", "BCscngbi txRX"},
	{"bozö", "bozjo", "bozO"},
	{"buä", "buja", "bujA"},
	{"buä-kɛ̂tɛ̂", "buja-kJxtJx", "bujA-KXTX"},
	{"buä-kötä", "buja-kjotja", "bujA-kOtA"},
	{"buä-mä-na-bɛ̂", "buja-mja-na-bJx", "bujA-mA-na-BX"},
	{"buä-mokönzi", "buja-mokjonzi", "bujA-mokOnzi"},
	{"buä-sû", "buja-sJu", "bujA-SU"},
	{"buäte", "bujate", "bujAte"},
	{"buä-tokua", "buja-tokua", "bujA-tokua"},
	{"buba", "buba", "buba"},
	{"bübä", "bjubja", "bUbA"},
	{"bübä", "bjubja", "bUbA"},
	{"bubu", "bubu", "bubu"},
	{"bûbu", "bJubu", "BUbu"},
	{"bûburû", "bJuburJu", "BUbuRU"},
	{"bubûtä", "bubJutja", "buBUtA"},
	{"bûku", "bJuku", "BUku"},
	{"bulɛ̂ɛ", "bulJxx", "buLXx"},
	{"bûngbi", "bJungbi", "BUngbi"},
	{"bûngbi", "bJungbi", "BUngbi"},
	{"bûngbi tɛrɛ̂", "bJungbi txrJx", "BUngbi txRX"},
	{"burü", "burju", "burU"},
	{"buruma", "buruma", "buruma"},
	{"bûsu", "bJusu", "BUsu"},
	{"butâni", "butJani", "buTAni"},
	{"butu", "butu", "butu"},
	{"butuma", "butuma", "butuma"},
	{"butuma", "butuma", "butuma"},
	{"butuma", "butuma", "butuma"},
	{"büzë", "bjuzje", "bUzE"},
	{"buzî", "buzJi", "buZI"},
	{"da", "da", "da"},
	{"da", "da", "da"},
	{"dä", "dja", "dA"},
	{"dä", "dja", "dA"},
	{"daä", "daja", "dajA"},
	{"daä", "daja", "dajA"},
	{"da bɛ̂", "da bJx", "da BX"},
	{"da-bɛ̂", "da-bJx", "da-BX"},
	{"da-kosâra", "da-kosJara", "da-koSAra"},
	{"dâlâmâ", "dJalJamJa", "DALAMA"},
	{"dâlë", "dJalje", "DAlE"},
	{"damâköngö", "damJakjongjo", "daMAkOngO"},
	{"damangɔ", "damangc", "damangc"},
	{"damazäni", "damazjani", "damazAni"},
	{"dambâ", "dambJa", "daMBA"},
	{"dâmi", "dJami", "DAmi"},
	{"damvɛnɛ", "damvxnx", "damvxnx"},
	{"da na bɛ̂", "da na bJx", "da na BX"},
	{"dândâ", "dJandJa", "DANDA"},
	{"dânga", "dJanga", "DAnga"},
	{"dangâlingâ", "dangJalingJa", "daNGAliNGA"},
	{"dangara", "dangara", "dangara"},
	{"dangbö", "dangbjo", "dangbO"},
	{"dangërë", "dangjerje", "dangErE"},
	{"dangi", "dangi", "dangi"},
	{"dara", "dara", "dara"},
	{"daräa", "darjaa", "darAa"},
	{"da-turu", "da-turu", "da-turu"},
	{"davɛkɛ", "davxkx", "davxkx"},
	{"dawäa", "dawjaa", "dawAa"},
	{"dawäa", "dawjaa", "dawAa"},
	{"dazo", "dazo", "dazo"},
	{"de", "de", "de"},
	{"dê", "dJe", "DE"},
	{"dë", "dje", "dE"},
	{"dɛ", "dx", "dx"},
	{"dɛ̈", "djx", "dX"},
	{"dɛ̈", "djx", "dX"},
	{"dɛ̈-bä", "djx-bja", "dX-bA"},
	{"dɛ̈bä", "djxbja", "dXbA"},
	{"dɛ̈bängɔ̈", "djxbjangjc", "dXbAngC"},
	{"dɛ̈-bä-nzɔ̈nî", "djx-bja-nzjcnJi", "dX-bA-nzCNI"},
	{"dɛ̈-bä-nzɔ̈nî na ndö tî", "djx-bja-nzjcnJi na ndjo tJi", "dX-bA-nzCNI na ndO TI"},
	{"dɛ̈-bä-sïɔ̈nî", "djx-bja-sjijcnJi", "dX-bA-sIjCNI"},
	{"dɛ̈-bä-sïɔ̈nî na ndö tî", "djx-bja-sjijcnJi na ndjo tJi", "dX-bA-sIjCNI na ndO TI"},
	{"dɛ̈-büzë", "djx-bjuzje", "dX-bUzE"},
	{"dêfa", "dJefa", "DEfa"},
	{"dɛ̈-kîtɛ", "djx-kJitx", "dX-KItx"},
	{"dɛ̈-kɔ̈ngɔ̈", "djx-kjcngjc", "dX-kCngC"},
	{"dɛku", "dxku", "dxku"},
	{"dema", "dema", "dema"},
	{"dëmängɔ̈-tɛrɛ̂", "djemjangjc-txrJx", "dEmAngC-txRX"},
	{"dema-tɛrɛ̂", "dema-txrJx", "dema-txRX"},
	{"dɛngbɛ", "dxngbx", "dxngbx"},
	{"dênge", "dJenge", "DEnge"},
	{"dêngi", "dJengi", "DEngi"},
	{"dëngɔ̈", "djengjc", "dEngC"},
	{"dɛ̈ngɔ̈", "djxngjc", "dXngC"},
	{"dɛ̈-nzɔ̈-bä", "djx-nzjc-bja", "dX-nzC-bA"},
	{"dɛ̈-nzɔ̈-bä na ndö tî", "djx-nzjc-bja na ndjo tJi", "dX-nzC-bA na ndO TI"},
	{"dɛrɛ̈", "dxrjx", "dxrX"},
	{"dɛ̈-sïɔ̈-bä", "djx-sjijc-bja", "dX-sIjC-bA"},
	{"dɛ̈-sïɔ̈-bä na ndö tî", "djx-sjijc-bja na ndjo tJi", "dX-sIjC-bA na ndO TI"},
	{"dɛ̈-yäkä", "djx-yjakja", "dX-yAkA"},
	{"di", "di", "di"},
	{"dî", "dJi", "DI"},
	{"dï", "dji", "dI"},
	{"didi", "didi", "didi"},
	{"dïdïrï", "djidjirji", "dIdIrI"},
	{"dï ïrï tî", "dji jirji tJi", "dI jIrI TI"},
	{"dïkï", "djikji", "dIkI"},
	{"dïkïnzï", "djikjinzji", "dIkInzI"},
	{"dîkɔ", "dJikc", "DIkc"},
	{"dîkɔ̂", "dJikJc", "DIKC"},
	{"do", "do", "do"},
	{"dɔ̂", "dJc", "DC"},
	{"dɔ̈", "djc", "dC"},
	{"dɔdɔ", "dcdc", "dcdc"},
	{"dɔ̈dɔ̈", "djcdjc", "dCdC"},
	{"dödörö", "djodjorjo", "dOdOrO"},
	{"dokpa", "dokpa", "dokpa"},
	{"dɔkpâlâ", "dckpJalJa", "dcKPALA"},
	{"doli", "doli", "doli"},
	{"dolö", "doljo", "dolO"},
	{"dɔ̈ na li", "djc na li", "dC na li"},
	{"dondö", "dondjo", "dondO"},
	{"dôndô", "dJondJo", "DONDO"},
	{"döngbä", "djongbja", "dOngbA"},
	{"dɔngɔ", "dcngc", "dcngc"},
	{"dɔngɔ̈", "dcngjc", "dcngC"},
	{"dɔngɔ̈ngbi", "dcngjcngbi", "dcngCngbi"},
	{"dɔngɔ̈ngbi", "dcngjcngbi", "dcngCngbi"},
	{"dɔngɔ̈ngbi tɛrɛ̂", "dcngjcngbi txrJx", "dcngCngbi txRX"},
	{"döpɔrɔ", "djopcrc", "dOpcrc"},
	{"dɔ̈rɔ̈", "djcrjc", "dCrC"},
	{"dɔrɔkɔ", "dcrckc", "dcrckc"},
	{"du", "du", "du"},
	{"dû", "dJu", "DU"},
	{"dü", "dju", "dU"},
	{"dudu", "dudu", "dudu"},
	{"duma", "duma", "duma"},
	{"düngɔ̈", "djungjc", "dUngC"},
	{"dû-ngû", "dJu-ngJu", "DU-NGU"},
	{"dûnîa", "dJunJia", "DUNIa"},
	{"dû-nyɛnɛ̈", "dJu-nyxnjx", "DU-nyxnX"},
	{"dûru", "dJuru", "DUru"},
	{"dutï", "dutji", "dutI"},
	{"dutï nzɔ̈nî", "dutji nzjcnJi", "dutI nzCNI"},
	{"ë", "je", "jE"},
	{"ɛ", "x", "x"},
	{"ë mvɛnî", "je mvxnJi", "jE mvxNI"},
	{"ere", "ere", "ere"},
	{"ɛrɛ", "xrx", "xrx"},
	{"ɛ̂rɛ̂gɛ", "JxrJxgx", "XRXgx"},
	{"fa", "fa", "fa"},
	{"fâ", "fJa", "FA"},
	{"fä", "fja", "fA"},
	{"fä", "fja", "fA"},
	{"fâa", "fJaa", "FAa"},
	{"fadë", "fadje", "fadE"},
	{"fadësô", "fadjesJo", "fadESO"},
	{"fafadësô", "fafadjesJo", "fafadESO"},
	{"fâla", "fJala", "FAla"},
	{"fâla mbïɔ̈", "fJala mbjijc", "FAla mbIjC"},
	{"fâla zûâ", "fJala zJuJa", "FAla ZUA"},
	{"fângbi", "fJangbi", "FAngbi"},
	{"fângbi", "fJangbi", "FAngbi"},
	{"fâ-nî", "fJa-nJi", "FA-NI"},
	{"fâra", "fJara", "FAra"},
	{"farânzi", "farJanzi", "faRAnzi"},
	{"farïni", "farjini", "farIni"},
	{"fên", "fJen", "FEN"},
	{"fɛ̂rɛ̂rɛ̂", "fJxrJxrJx", "FXRXRX"},
	{"fi", "fi", "fi"},
	{"fîmbo", "fJimbo", "FImbo"},
	{"fingi", "fingi", "fingi"},
	{"finî", "finJi", "fiNI"},
	{"finî", "finJi", "fiNI"},
	{"finön", "finjon", "finON"},
	{"fo", "fo", "fo"},
	{"fö", "fjo", "fO"},
	{"föndo", "fjondo", "fOndo"},
	{"fɔndɔ", "fcndc", "fcndc"},
	{"fɔnɔ", "fcnc", "fcnc"},
	{"fɔ̈nɔ̈", "fjcnjc", "fCnC"},
	{"fû", "fJu", "FU"},
	{"fü", "fju", "fU"},
	{"fufû", "fufJu", "fuFU"},
	{"fufû", "fufJu", "fuFU"},
	{"fufulafu", "fufulafu", "fufulafu"},
	{"fûku", "fJuku", "FUku"},
	{"fulundïngi", "fulundjingi", "fulundIngi"},
	{"fûn", "fJun", "FUN"},
	{"fün", "fjun", "fUN"},
	{"fungâ", "fungJa", "fuNGA"},
	{"fûnga", "fJunga", "FUnga"},
	{"fungûla", "fungJula", "fuNGUla"},
	{"fungûla", "fungJula", "fuNGUla"},
	{"fünngɔ̈", "fjunngjc", "fUNngC"},
	{"fûru", "fJuru", "FUru"},
	{"fûru", "fJuru", "FUru"},
	{"fûta", "fJuta", "FUta"},
	{"fûta", "fJuta", "FUta"},
	{"füu", "fjuu", "fUu"},
	{"ga-", "ga-", "ga-"},
	{"gä", "gja", "gA"},
	{"gä", "gja", "gA"},
	{"gagi", "gagi", "gagi"},
	{"gana", "gana", "gana"},
	{"gana", "gana", "gana"},
	{"gä na", "gja na", "gA na"},
	{"gânda", "gJanda", "GAnda"},
	{"gängä", "gjangja", "gAngA"},
	{"gângârâ", "gJangJarJa", "GANGARA"},
	{"gangba", "gangba", "gangba"},
	{"gângbi", "gJangbi", "GAngbi"},
	{"gângbi", "gJangbi", "GAngbi"},
	{"gängɔ̈", "gjangjc", "gAngC"},
	{"ganzâ", "ganzJa", "gaNZA"},
	{"gao", "gao", "gao"},
	{"gapa", "gapa", "gapa"},
	{"gara", "gara", "gara"},
	{"garâ", "garJa", "gaRA"},
	{"gasa", "gasa", "gasa"},
	{"gasa", "gasa", "gasa"},
	{"gatï", "gatji", "gatI"},
	{"gba", "gba", "gba"},
	{"gba", "gba", "gba"},
	{"gbâ", "gbJa", "GBA"},
	{"gbâ", "gbJa", "GBA"},
	{"gbä", "gbja", "gbA"},
	{"gbadöla", "gbadjola", "gbadOla"},
	{"gbafu", "gbafu", "gbafu"},
	{"gbagä", "gbagja", "gbagA"},
	{"gbägbä", "gbjagbja", "gbAgbA"},
	{"gbägbä", "gbjagbja", "gbAgbA"},
	{"gbägbä", "gbjagbja", "gbAgbA"},
	{"gbagbara", "gbagbara", "gbagbara"},
	{"gbâgbârâ", "gbJagbJarJa", "GBAGBARA"},
	{"gbâka", "gbJaka", "GBAka"},
	{"gbâkarâgba", "gbJakarJagba", "GBAkaRAgba"},
	{"gbakô", "gbakJo", "gbaKO"},
	{"gbâkûrû", "gbJakJurJu", "GBAKURU"},
	{"gbalâka", "gbalJaka", "gbaLAka"},
	{"gba-mbîngo", "gba-mbJingo", "gba-MBIngo"},
	{"gba-na-mbänä", "gba-na-mbjanja", "gba-na-mbAnA"},
	{"gbânda", "gbJanda", "GBAnda"},
	{"gbândä", "gbJandja", "GBAndA"},
	{"gbânda-sango", "gbJanda-sango", "GBAnda-sango"},
	{"gbânda tî tɛrɛ", "gbJanda tJi txrx", "GBAnda TI txrx"},
	{"gbängä", "gbjangja", "gbAngA"},
	{"gbanza", "gbanza", "gbanza"},
	{"gbânzi", "gbJanzi", "GBAnzi"},
	{"gbanzia", "gbanzia", "gbanzia"},
	{"gbara", "gbara", "gbara"},
	{"gbara", "gbara", "gbara"},
	{"gbaragaza", "gbaragaza", "gbaragaza"},
	{"gbârâka", "gbJarJaka", "GBARAka"},
	{"gbari", "gbari", "gbari"},
	{"gbätä", "gbjatja", "gbAtA"},
	{"gbâzâ", "gbJazJa", "GBAZA"},
	{"gbâzâ-bängâ", "gbJazJa-bjangJa", "GBAZA-bANGA"},
	{"gbäzägbö", "gbjazjagbjo", "gbAzAgbO"},
	{"gbë", "gbje", "gbE"},
	{"gbɛ", "gbx", "gbx"},
	{"gbɛ̈ɛ", "gbjxx", "gbXx"},
	{"gbefâ", "gbefJa", "gbeFA"},
	{"gbɛgbɛ̈rɛ", "gbxgbjxrx", "gbxgbXrx"},
	{"gbɛ-lɛ̂", "gbx-lJx", "gbx-LX"},
	{"gbêlêwele", "gbJelJewele", "GBELEwele"},
	{"gbɛnɛ", "gbxnx", "gbxnx"},
	{"gbɛ̈nɛ̈", "gbjxnjx", "gbXnX"},
	{"gbênga", "gbJenga", "GBEnga"},
	{"gbêngbi", "gbJengbi", "GBEngbi"},
	{"gbêngbi tɛrɛ̂", "gbJengbi txrJx", "GBEngbi txRX"},
	{"gbêngbi tɛrɛ̂", "gbJengbi txrJx", "GBEngbi txRX"},
	{"gbɛ-nyön-gbïä", "gbx-nyjon-gbjija", "gbx-nyON-gbIjA"},
	{"gbenzï", "gbenzji", "gbenzI"},
	{"gbɛrɛ̂", "gbxrJx", "gbxRX"},
	{"gbï", "gbji", "gbI"},
	{"gbï", "gbji", "gbI"},
	{"gbïä", "gbjija", "gbIjA"},
	{"gbîangbi", "gbJiangbi", "GBIangbi"},
	{"gbigbi", "gbigbi", "gbigbi"},
	{"gbikï", "gbikji", "gbikI"},
	{"gbïngɔ̈", "gbjingjc", "gbIngC"},
	{"gbogbo", "gbogbo", "gbogbo"},
	{"gbôgbôlinda", "gbJogbJolinda", "GBOGBOlinda"},
	{"gbôkôrô", "gbJokJorJo", "GBOKORO"},
	{"gbɔ-ngû", "gbc-ngJu", "gbc-NGU"},
	{"gbɔ̈ɔ", "gbjcc", "gbCc"},
	{"gbɔrɔ", "gbcrc", "gbcrc"},
	{"gbɔrɔngâne", "gbcrcngJane", "gbcrcNGAne"},
	{"gbɔ-tɛ", "gbc-tx", "gbc-tx"},
	{"gbɔ̂tɔ", "gbJctc", "GBCtc"},
	{"gbû", "gbJu", "GBU"},
	{"gbugburu", "gbugburu", "gbugburu"},
	{"gbugburu", "gbugburu", "gbugburu"},
	{"gbuügbuü", "gbujugbuju", "gbujUgbujU"},
	{"ge", "ge", "ge"},
	{"gêkôrô", "gJekJorJo", "GEKORO"},
	{"gɛnɛ", "gxnx", "gxnx"},
	{"genia", "genia", "genia"},
	{"gɛ̈nyɛ̈ngɔ̈", "gjxnyjxngjc", "gXnyXngC"},
	{"gɛrɛ̂", "gxrJx", "gxRX"},
	{"gɛrɛ̂", "gxrJx", "gxRX"},
	{"gɛrɛrɛ", "gxrxrx", "gxrxrx"},
	{"gɛrɛrɛ", "gxrxrx", "gxrxrx"},
	{"gɛrɛ̂-wüngɔ̈", "gxrJx-wjungjc", "gxRX-wUngC"},
	{"gɛ̈tɛ̈", "gjxtjx", "gXtX"},
	{"gi", "gi", "gi"},
	{"gï", "gji", "gI"},
	{"gîâ", "gJiJa", "GIA"},
	{"gi bɛ̂", "gi bJx", "gi BX"},
	{"gi-bɛ̂", "gi-bJx", "gi-BX"},
	{"gidi", "gidi", "gidi"},
	{"gïgî", "gjigJi", "gIGI"},
	{"gilisa", "gilisa", "gilisa"},
	{"gi na bɛ̂", "gi na bJx", "gi na BX"},
	{"gindî", "gindJi", "giNDI"},
	{"gïngɔ̈", "gjingjc", "gIngC"},
	{"ginon", "ginon", "ginoN"},
	{"giɔ", "gic", "gic"},
	{"giriri", "giriri", "giriri"},
	{"gɔ̂", "gJc", "GC"},
	{"gobi", "gobi", "gobi"},
	{"gɔbɔ", "gcbc", "gcbc"},
	{"gɔdɔbe", "gcdcbe", "gcdcbe"},
	{"gögö", "gjogjo", "gOgO"},
	{"gɔgɔrɔ", "gcgcrc", "gcgcrc"},
	{"gögüä", "gjogjuja", "gOgUjA"},
	{"gɔigɔ̂î", "gcigJcJi", "gciGCI"},
	{"gön", "gjon", "gON"},
	{"gônda", "gJonda", "GOnda"},
	{"gônda", "gJonda", "GOnda"},
	{"gɔ̂rɔ", "gJcrc", "GCrc"},
	{"gɔ̂rɔ", "gJcrc", "GCrc"},
	{"gɔ̂rɔ", "gJcrc", "GCrc"},
	{"gôsâ", "gJosJa", "GOSA"},
	{"gôyongö", "gJoyongjo", "GOyongO"},
	{"gɔzɔ", "gczc", "gczc"},
	{"gua", "gua", "gua"},
	{"gûâ", "gJuJa", "GUA"},
	{"guagua", "guagua", "guagua"},
	{"güägüä", "gjujagjuja", "gUjAgUjA"},
	{"gue", "gue", "gue"},
	{"gue na", "gue na", "gue na"},
	{"gue nzɔ̈nî", "gue nzjcnJi", "gue nzCNI"},
	{"gügü", "gjugju", "gUgU"},
	{"gügümä", "gjugjumja", "gUgUmA"},
	{"gugûrû", "gugJurJu", "guGURU"},
	{"gûî", "gJuJi", "GUI"},
	{"gümbâyä", "gjumbJayja", "gUMBAyA"},
	{"gümbâyä", "gjumbJayja", "gUMBAyA"},
	{"gündâ", "gjundJa", "gUNDA"},
	{"gûrû", "gJurJu", "GURU"},
	{"gürü", "gjurju", "gUrU"},
	{"hä", "hja", "hA"},
	{"hâa", "hJaa", "HAa"},
	{"hâka", "hJaka", "HAka"},
	{"häkängɔ̈", "hjakjangjc", "hAkAngC"},
	{"häko", "hjako", "hAko"},
	{"halë", "halje", "halE"},
	{"hân", "hJan", "HAN"},
	{"hânda", "hJanda", "HAnda"},
	{"hânda", "hJanda", "HAnda"},
	{"hâriya", "hJariya", "HAriya"},
	{"he", "he", "he"},
	{"hë", "hje", "hE"},
	{"hɛnɛ", "hxnx", "hxnx"},
	{"hɛ̈nɛ̈", "hjxnjx", "hXnX"},
	{"he ngîâ", "he ngJiJa", "he NGIA"},
	{"hînga", "hJinga", "HInga"},
	{"hïngängɔ̈", "hjingjangjc", "hIngAngC"},
	{"hîni", "hJini", "HIni"},
	{"hîni", "hJini", "HIni"},
	{"hîo", "hJio", "HIo"},
	{"hîo-hîo", "hJio-hJio", "HIo-HIo"},
	{"hömba", "hjomba", "hOmba"},
	{"hôn", "hJon", "HON"},
	{"hɔ̈n", "hjcn", "hCN"},
	{"hɔ̂ndɛ", "hJcndx", "HCndx"},
	{"hɔ̈ndɛ̈ngɔ̈", "hjcndjxngjc", "hCndXngC"},
	{"hɔ̂ndɛ-sïɔ̈-yê", "hJcndx-sjijc-yJe", "HCndx-sIjC-YE"},
	{"hôn-gɛrɛ̂", "hJon-gxrJx", "HON-gxRX"},
	{"hɔ̈ngɔ̈", "hjcngjc", "hCngC"},
	{"hɔ̈n ndɔ̈ tî", "hjcn ndjc tJi", "hCN ndC TI"},
	{"hôntï", "hJontji", "HONtI"},
	{"hû", "hJu", "HU"},
	{"hûlɛ", "hJulx", "HUlx"},
	{"hülë", "hjulje", "hUlE"},
	{"hülɛ̈ngɔ̈", "hjuljxngjc", "hUlXngC"},
	{"hülɛ̈ngɔ̈", "hjuljxngjc", "hUlXngC"},
	{"hûnda", "hJunda", "HUnda"},
	{"hûnda", "hJunda", "HUnda"},
	{"hunu", "hunu", "hunu"},
	{"hûnzi", "hJunzi", "HUnzi"},
	{"huru", "huru", "huru"},
	{"hürü", "hjurju", "hUrU"},
	{"ï", "ji", "jI"},
	{"ï mvɛnî", "ji mvxnJi", "jI mvxNI"},
	{"in", "in", "iN"},
	{"îngɔ̈", "Jingjc", "IngC"},
	{"in-in", "in-in", "iN-iN"},
	{"înɔ̈", "Jinjc", "InC"},
	{"îri", "Jiri", "Iri"},
	{"ïrï", "jirji", "jIrI"},
	{"îtä", "Jitja", "ItA"},
	{"îtä-buä", "Jitja-buja", "ItA-bujA"},
	{"ka", "ka", "ka"},
	{"kâ", "kJa", "KA"},
	{"kâ", "kJa", "KA"},
	{"kä", "kja", "kA"},
	{"kä", "kja", "kA"},
	{"kâbî", "kJabJi", "KABI"},
	{"kabinêe", "kabinJee", "kabiNEe"},
	{"kadâ", "kadJa", "kaDA"},
	{"kâfe", "kJafe", "KAfe"},
	{"kaga", "kaga", "kaga"},
	{"kâi", "kJai", "KAi"},
	{"kâî", "kJaJi", "KAI"},
	{"kakâ", "kakJa", "kaKA"},
	{"kakâ", "kakJa", "kaKA"},
	{"kakara", "kakara", "kakara"},
	{"kakauka", "kakauka", "kakauka"},
	{"käkërë", "kjakjerje", "kAkErE"},
	{"kakö", "kakjo", "kakO"},
	{"käkorö", "kjakorjo", "kAkorO"},
	{"kalâ", "kalJa", "kaLA"},
	{"kalambo", "kalambo", "kalambo"},
	{"kamâta", "kamJata", "kaMAta"},
	{"kamâta", "kamJata", "kaMAta"},
	{"kamba", "kamba", "kamba"},
	{"kâmba", "kJamba", "KAmba"},
	{"kambirï", "kambirji", "kambirI"},
	{"kambirï", "kambirji", "kambirI"},
	{"kambîri", "kambJiri", "kaMBIri"},
	{"kambisa", "kambisa", "kambisa"},
	{"kambisä", "kambisja", "kambisA"},
	{"kämbûsu", "kjambJusu", "kAMBUsu"},
	{"kamɛ̈nɛ̈", "kamjxnjx", "kamXnX"},
	{"kanâna", "kanJana", "kaNAna"},
	{"kandä", "kandja", "kandA"},
	{"kandâa", "kandJaa", "kaNDAa"},
	{"kânga", "kJanga", "KAnga"},
	{"kânga", "kJanga", "KAnga"},
	{"kângâ", "kJangJa", "KANGA"},
	{"kângâ", "kJangJa", "KANGA"},
	{"kangamä", "kangamja", "kangamA"},
	{"kangba", "kangba", "kangba"},
	{"kangba", "kangba", "kangba"},
	{"kângbâ", "kJangbJa", "KANGBA"},
	{"kängbä", "kjangbja", "kAngbA"},
	{"kângbi", "kJangbi", "KAngbi"},
	{"kângbi", "kJangbi", "KAngbi"},
	{"kângbi tɛrɛ̂", "kJangbi txrJx", "KAngbi txRX"},
	{"kangi", "kangi", "kangi"},
	{"kängɔ̈", "kjangjc", "kAngC"},
	{"kangoya", "kangoya", "kangoya"},
	{"kânyâ", "kJanyJa", "KANYA"},
	{"kanza", "kanza", "kanza"},
	{"kanzagɔ̈", "kanzagjc", "kanzagC"},
	{"kapï", "kapji", "kapI"},
	{"kapitäni", "kapitjani", "kapitAni"},
	{"kara", "kara", "kara"},
	{"kâra", "kJara", "KAra"},
	{"kârâ", "kJarJa", "KARA"},
	{"karagba", "karagba", "karagba"},
	{"kârâgɔrɔ̈", "kJarJagcrjc", "KARAgcrC"},
	{"kârâkö", "kJarJakjo", "KARAkO"},
	{"karangbâ", "karangbJa", "karaNGBA"},
	{"kâsa", "kJasa", "KAsa"},
	{"kasakasa", "kasakasa", "kasakasa"},
	{"kasï", "kasji", "kasI"},
	{"katɛ", "katx", "katx"},
	{"katikâti", "katikJati", "katiKAti"},
	{"kätîsima", "kjatJisima", "kATIsima"},
	{"kâwa", "kJawa", "KAwa"},
	{"kawoya", "kawoya", "kawoya"},
	{"kayë", "kayje", "kayE"},
	{"kayëe", "kayjee", "kayEe"},
	{"kɛ", "kx", "kx"},
	{"kɛ̈kɛ̈", "kjxkjx", "kXkX"},
	{"kɛkɛrɛ", "kxkxrx", "kxkxrx"},
	{"kêkerêke", "kJekerJeke", "KEkeREke"},
	{"kêlê", "kJelJe", "KELE"},
	{"kɛ̂lɛ̂lɛ̂", "kJxlJxlJx", "KXLXLX"},
	{"kêma", "kJema", "KEma"},
	{"kɛmbɛ", "kxmbx", "kxmbx"},
	{"kênda", "kJenda", "KEnda"},
	{"kɛ̂nɛ", "kJxnx", "KXnx"},
	{"kɛ̈nɛ̈", "kjxnjx", "kXnX"},
	{"kɛ̈ngɛ̈", "kjxngjx", "kXngX"},
	{"kengêre", "kengJere", "keNGEre"},
	{"kɛ̈ngɔ̈", "kjxngjc", "kXngC"},
	{"kepaka", "kepaka", "kepaka"},
	{"kepakara", "kepakara", "kepakara"},
	{"kɛ̂rɛ̈", "kJxrjx", "KXrX"},
	{"kerebende", "kerebende", "kerebende"},
	{"kerebende", "kerebende", "kerebende"},
	{"kerekpa", "kerekpa", "kerekpa"},
	{"kerekpä", "kerekpja", "kerekpA"},
	{"kɛ̂tɛ̂", "kJxtJx", "KXTX"},
	{"kɛ̂tɛ̂", "kJxtJx", "KXTX"},
	{"kɛ̂tɛ̂", "kJxtJx", "KXTX"},
	{"kɛ̂tɛ̂-babâ", "kJxtJx-babJa", "KXTX-baBA"},
	{"kɛ̂tɛ̂-îtä", "kJxtJx-Jitja", "KXTX-ItA"},
	{"kɛ̂tɛ̂-mamâ", "kJxtJx-mamJa", "KXTX-maMA"},
	{"kî", "kJi", "KI"},
	{"kî", "kJi", "KI"},
	{"kîki", "kJiki", "KIki"},
	{"kinda", "kinda", "kinda"},
	{"kindânda", "kindJanda", "kiNDAnda"},
	{"kïndängɔ̈", "kjindjangjc", "kIndAngC"},
	{"kindë", "kindje", "kindE"},
	{"kîndɛ̂rɛ̂", "kJindJxrJx", "KINDXRX"},
	{"kinîni", "kinJini", "kiNIni"},
	{"kîɔ", "kJic", "KIc"},
	{"kîri", "kJiri", "KIri"},
	{"kîrîkiri", "kJirJikiri", "KIRIkiri"},
	{"kîrîkiri", "kJirJikiri", "KIRIkiri"},
	{"kïrïngɔ̈", "kjirjingjc", "kIrIngC"},
	{"kîrɔ̂", "kJirJc", "KIRC"},
	{"kisɔrɔ", "kiscrc", "kiscrc"},
	{"kîtɛ", "kJitx", "KItx"},
	{"kîti", "kJiti", "KIti"},
	{"kîzi", "kJizi", "KIzi"},
	{"kô", "kJo", "KO"},
	{"kö", "kjo", "kO"},
	{"kö", "kjo", "kO"},
	{"kɔ̂", "kJc", "KC"},
	{"kɔ̂-", "kJc-", "KC-"},
	{"kɔ̂bɛ", "kJcbx", "KCbx"},
	{"kobêla", "kobJela", "koBEla"},
	{"kobêla tî wâ", "kobJela tJi wJa", "koBEla TI WA"},
	{"kɔdɛ̈", "kcdjx", "kcdX"},
	{"kɔdɛ̈-", "kcdjx-", "kcdX-"},
	{"kɔdɛ̈kua", "kcdjxkua", "kcdXkua"},
	{"kɔ̈dɔ̈rɔ̈", "kjcdjcrjc", "kCdCrC"},
	{"kɔ̈dɔ̈rɔ̈-sêse", "kjcdjcrjc-sJese", "kCdCrC-SEse"},
	{"kɔ̈garä", "kjcgarja", "kCgarA"},
	{"kɔï", "kcji", "kcjI"},
	{"kɔï", "kcji", "kcjI"},
	{"kɔï", "kcji", "kcjI"},
	{"kôkâ", "kJokJa", "KOKA"},
	{"kôko", "kJoko", "KOko"},
	{"kɔkɔ", "kckc", "kckc"},
	{"kɔ̂kɔ̂", "kJckJc", "KCKC"},
	{"kɔkɔmbɛ", "kckcmbx", "kckcmbx"},
	{"kɔkɔra", "kckcra", "kckcra"},
	{"koli", "koli", "koli"},
	{"kɔ̂lï", "kJclji", "KClI"},
	{"kɔ̂lï", "kJclji", "KClI"},
	{"kɔ̂lï", "kJclji", "KClI"},
	{"kɔ̂lï-", "kJclji-", "KClI-"},
	{"kɔ̂lï-kɔ̂lï", "kJclji-kJclji", "KClI-KClI"},
	{"kolîngo", "kolJingo", "koLIngo"},
	{"kɔ̂-li-tï", "kJc-li-tji", "KC-li-tI"},
	{"kɔ̂lï-wâlï", "kJclji-wJalji", "KClI-WAlI"},
	{"kôlo", "kJolo", "KOlo"},
	{"kolôfîa", "kolJofJia", "koLOFIa"},
	{"kɔ̂lɔ̈kɔ̂tɔ̈", "kJcljckJctjc", "KClCKCtC"},
	{"kolôngo", "kolJongo", "koLOngo"},
	{"kɔlɔngɔ", "kclcngc", "kclcngc"},
	{"kömbë", "kjombje", "kOmbE"},
	{"kömbë", "kjombje", "kOmbE"},
	{"kɔmberëe", "kcmberjee", "kcmberEe"},
	{"kombûka", "kombJuka", "koMBUka"},
	{"kombûka", "kombJuka", "koMBUka"},
	{"kɔmɛ", "kcmx", "kcmx"},
	{"kɔ̂ndɔ", "kJcndc", "KCndc"},
	{"konga", "konga", "konga"},
	{"kongä", "kongja", "kongA"},
	{"kongba", "kongba", "kongba"},
	{"kongba", "kongba", "kongba"},
	{"köngbä", "kjongbja", "kOngbA"},
	{"kongɔ̈", "kongjc", "kongC"},
	{"kongɔ̈", "kongjc", "kongC"},
	{"kôngô", "kJongJo", "KONGO"},
	{"köngɔ̈", "kjongjc", "kOngC"},
	{"kɔngɔ̈", "kcngjc", "kcngC"},
	{"kɔ̈ngɔ̈", "kjcngjc", "kCngC"},
	{"kɔnɔ", "kcnc", "kcnc"},
	{"kɔnɔ̂", "kcnJc", "kcNC"},
	{"kɔ̈nɔ̈ngɔ̈", "kjcnjcngjc", "kCnCngC"},
	{"konza", "konza", "konza"},
	{"kɔnzɔ̈ngɔ̈rɔ̈", "kcnzjcngjcrjc", "kcnzCngCrC"},
	{"kopo", "kopo", "kopo"},
	{"kɔ̈pɔ̈", "kjcpjc", "kCpC"},
	{"kôro", "kJoro", "KOro"},
	{"kɔrɔ", "kcrc", "kcrc"},
	{"kɔ̈rɔ̈", "kjcrjc", "kCrC"},
	{"korobö", "korobjo", "korobO"},
	{"korôkongbô", "korJokongbJo", "koROkoNGBO"},
	{"körömëngë", "kjorjomjengje", "kOrOmEngE"},
	{"korôro", "korJoro", "koROro"},
	{"kosâla", "kosJala", "koSAla"},
	{"kosâra", "kosJara", "koSAra"},
	{"kɔ̈sï", "kjcsji", "kCsI"},
	{"kɔsɔ", "kcsc", "kcsc"},
	{"kɔ̂sɔ", "kJcsc", "KCsc"},
	{"kɔ̂sɔ̈", "kJcsjc", "KCsC"},
	{"kɔsɔ tî ngonda", "kcsc tJi ngonda", "kcsc TI ngonda"},
	{"kötä", "kjotja", "kOtA"},
	{"kötä", "kjotja", "kOtA"},
	{"kötä-babâ", "kjotja-babJa", "kOtA-baBA"},
	{"kötä-bɛ̈", "kjotja-bjx", "kOtA-bX"},
	{"kötä-buä", "kjotja-buja", "kOtA-bujA"},
	{"kötä-îtä", "kjotja-Jitja", "kOtA-ItA"},
	{"kötä-mamâ", "kjotja-mamJa", "kOtA-maMA"},
	{"kötä ngû", "kjotja ngJu", "kOtA NGU"},
	{"kötarä", "kjotarja", "kOtarA"},
	{"kötä-zo", "kjotja-zo", "kOtA-zo"},
	{"kɔ̈tï", "kjctji", "kCtI"},
	{"koto", "koto", "koto"},
	{"kôto", "kJoto", "KOto"},
	{"kɔtɔ", "kctc", "kctc"},
	{"kɔtɔ", "kctc", "kctc"},
	{"kɔtɔ̈ɔn", "kctjccn", "kctCcN"},
	{"kôya", "kJoya", "KOya"},
	{"kôya", "kJoya", "KOya"},
	{"kɔ̂zɔ", "kJczc", "KCzc"},
	{"kɔ̂zɔ", "kJczc", "KCzc"},
	{"kɔ̂zɔnî", "kJczcnJi", "KCzcNI"},
	{"kɔ̂zɔ tî", "kJczc tJi", "KCzc TI"},
	{"kpa", "kpa", "kpa"},
	{"kpâ", "kpJa", "KPA"},
	{"kpâa", "kpJaa", "KPAa"},
	{"kpâa", "kpJaa", "KPAa"},
	{"kpaka", "kpaka", "kpaka"},
	{"kpaka-ta", "kpaka-ta", "kpaka-ta"},
	{"kpäkpä", "kpjakpja", "kpAkpA"},
	{"kpâlâköngö", "kpJalJakjongjo", "KPALAkOngO"},
	{"kpälë", "kpjalje", "kpAlE"},
	{"kpängäbä", "kpjangjabja", "kpAngAbA"},
	{"kpangba", "kpangba", "kpangba"},
	{"kpangbara", "kpangbara", "kpangbara"},
	{"kpangbara", "kpangbara", "kpangbara"},
	{"kpângbârâ", "kpJangbJarJa", "KPANGBARA"},
	{"kpängbärä", "kpjangbjarja", "kpAngbArA"},
	{"kpângi", "kpJangi", "KPAngi"},
	{"kpätä", "kpjatja", "kpAtA"},
	{"kpë", "kpje", "kpE"},
	{"kpɛ̂", "kpJx", "KPX"},
	{"kpɛ̈", "kpjx", "kpX"},
	{"kpɛ̈", "kpjx", "kpX"},
	{"kpêe", "kpJee", "KPEe"},
	{"kpêkê", "kpJekJe", "KPEKE"},
	{"kpêkê-ûse", "kpJekJe-Juse", "KPEKE-Use"},
	{"kpë-li", "kpje-li", "kpE-li"},
	{"kpɛ̈ mbɛtɔ", "kpjx mbxtc", "kpX mbxtc"},
	{"kpenda", "kpenda", "kpenda"},
	{"kpëngba", "kpjengba", "kpEngba"},
	{"kpëngbä", "kpjengbja", "kpEngbA"},
	{"kpëngbängɔ̈", "kpjengbjangjc", "kpEngbAngC"},
	{"kpɛ̈ngbɛ̈rɛ̈", "kpjxngbjxrjx", "kpXngbXrX"},
	{"kpere", "kpere", "kpere"},
	{"kpɛrɛkpɛrɛ", "kpxrxkpxrx", "kpxrxkpxrx"},
	{"kpɛtɛ", "kpxtx", "kpxtx"},
	{"kpîkara", "kpJikara", "KPIkara"},
	{"kpɔ", "kpc", "kpc"},
	{"kpɔ̂", "kpJc", "KPC"},
	{"kpöka", "kpjoka", "kpOka"},
	{"kpôkpô", "kpJokpJo", "KPOKPO"},
	{"kpɔrɔ", "kpcrc", "kpcrc"},
	{"kpɔtɔ", "kpctc", "kpctc"},
	{"kpu", "kpu", "kpu"},
	{"kpû", "kpJu", "KPU"},
	{"kpû-kângbi", "kpJu-kJangbi", "KPU-KAngbi"},
	{"kpûkpû", "kpJukpJu", "KPUKPU"},
	{"kpûkû", "kpJukJu", "KPUKU"},
	{"kpunakpu", "kpunakpu", "kpunakpu"},
	{"kpunakpu", "kpunakpu", "kpunakpu"},
	{"kpütä", "kpjutja", "kpUtA"},
	{"kpû-tɛ̂ngbi", "kpJu-tJxngbi", "KPU-TXngbi"},
	{"ku", "ku", "ku"},
	{"kü", "kju", "kU"},
	{"kua", "kua", "kua"},
	{"kûâ", "kJuJa", "KUA"},
	{"küä", "kjuja", "kUjA"},
	{"kualë", "kualje", "kualE"},
	{"kûɛ̂", "kJuJx", "KUX"},
	{"kûɛ̂", "kJuJx", "KUX"},
	{"kugbë", "kugbje", "kugbE"},
	{"kûîi", "kJuJii", "KUIi"},
	{"kûîi", "kJuJii", "KUIi"},
	{"kûku", "kJuku", "KUku"},
	{"kûku", "kJuku", "KUku"},
	{"kûkurû", "kJukurJu", "KUkuRU"},
	{"kûkürû", "kJukjurJu", "KUkURU"},
	{"kükürü", "kjukjurju", "kUkUrU"},
	{"kulü", "kulju", "kulU"},
	{"kûma", "kJuma", "KUma"},
	{"kunda", "kunda", "kunda"},
	{"kundâ", "kundJa", "kuNDA"},
	{"kundi", "kundi", "kundi"},
	{"kûngbâ", "kJungbJa", "KUNGBA"},
	{"kûngbi", "kJungbi", "KUngbi"},
	{"kûngbi", "kJungbi", "KUngbi"},
	{"kûngü", "kJungju", "KUngU"},
	{"kupu", "kupu", "kupu"},
	{"kürä", "kjurja", "kUrA"},
	{"kürü", "kjurju", "kUrU"},
	{"kûrûkürü", "kJurJukjurju", "KURUkUrU"},
	{"kürüngü", "kjurjungju", "kUrUngU"},
	{"kusâla", "kusJala", "kuSAla"},
	{"kusâra", "kusJara", "kuSAra"},
	{"kûtu", "kJutu", "KUtu"},
	{"kûtu", "kJutu", "KUtu"},
	{"kûtu", "kJutu", "KUtu"},
	{"kûtu-", "kJutu-", "KUtu-"},
	{"kûtu-gɛrɛ̈", "kJutu-gxrjx", "KUtu-gxrX"},
	{"kutukutu", "kutukutu", "kutukutu"},
	{"kuzü", "kuzju", "kuzU"},
	{"lâ", "lJa", "LA"},
	{"lâ", "lJa", "LA"},
	{"laä", "laja", "lajA"},
	{"lâbâdâ", "lJabJadJa", "LABADA"},
	{"lägbädä", "ljagbjadja", "lAgbAdA"},
	{"lâi", "lJai", "LAi"},
	{"lakërë", "lakjerje", "lakErE"},
	{"lakpängbä", "lakpjangbja", "lakpAngbA"},
	{"lâkûɛ̂", "lJakJuJx", "LAKUX"},
	{"lâkûɛ̂-lâkûɛ̂", "lJakJuJx-lJakJuJx", "LAKUX-LAKUX"},
	{"lâ-kûî", "lJa-kJuJi", "LA-KUI"},
	{"lâmbâ", "lJambJa", "LAMBA"},
	{"lando", "lando", "lando"},
	{"langä", "langja", "langA"},
	{"längɔ̈", "ljangjc", "lAngC"},
	{"längɔ̈", "ljangjc", "lAngC"},
	{"längɔ̈", "ljangjc", "lAngC"},
	{"lâ-nî", "lJa-nJi", "LA-NI"},
	{"lâ-nî-sô", "lJa-nJi-sJo", "LA-NI-SO"},
	{"lapärä", "lapjarja", "lapArA"},
	{"lâ-pɔ̂sɔ", "lJa-pJcsc", "LA-PCsc"},
	{"lâ-sô", "lJa-sJo", "LA-SO"},
	{"lavu", "lavu", "lavu"},
	{"lâ-wa", "lJa-wa", "LA-wa"},
	{"lawü", "lawju", "lawU"},
	{"lâ-yenga", "lJa-yenga", "LA-yenga"},
	{"lê", "lJe", "LE"},
	{"lë", "lje", "lE"},
	{"lɛ̂", "lJx", "LX"},
	{"lɛ̈", "ljx", "lX"},
	{"lêgë", "lJegje", "LEgE"},
	{"lêgë-ɔ̂kɔ", "lJegje-Jckc", "LEgE-Ckc"},
	{"lɛkɛ", "lxkx", "lxkx"},
	{"lɛkɛrɛ", "lxkxrx", "lxkxrx"},
	{"lekpa", "lekpa", "lekpa"},
	{"lele", "lele", "lele"},
	{"lêlê", "lJelJe", "LELE"},
	{"lëlë", "ljelje", "lElE"},
	{"lɛlɛ", "lxlx", "lxlx"},
	{"lɛ̈lɛ̈", "ljxljx", "lXlX"},
	{"lembe", "lembe", "lembe"},
	{"lëndâ", "ljendJa", "lENDA"},
	{"lendë", "lendje", "lendE"},
	{"lêngbêtɔ̂rɔ̂", "lJengbJetJcrJc", "LENGBETCRC"},
	{"lenge", "lenge", "lenge"},
	{"lɛ̂ngua", "lJxngua", "LXngua"},
	{"lɛ̂-tî-bëkpä", "lJx-tJi-bjekpja", "LX-TI-bEkpA"},
	{"lɛ̂-tî-mbɛ̈tï", "lJx-tJi-mbjxtji", "LX-TI-mbXtI"},
	{"lɛ̂-tî-ndö", "lJx-tJi-ndjo", "LX-TI-ndO"},
	{"lê-yäkä", "lJe-yjakja", "LE-yAkA"},
	{"li", "li", "li"},
	{"li", "li", "li"},
	{"li", "li", "li"},
	{"li", "li", "li"},
	{"li", "li", "li"},
	{"lï", "lji", "lI"},
	{"lï", "lji", "lI"},
	{"lîâ", "lJiJa", "LIA"},
	{"lîfïlo", "lJifjilo", "LIfIlo"},
	{"likisi", "likisi", "likisi"},
	{"likɔngɔ̂", "likcngJc", "likcNGC"},
	{"likundû", "likundJu", "likuNDU"},
	{"li-kûnɛ", "li-kJunx", "li-KUnx"},
	{"linda", "linda", "linda"},
	{"linda", "linda", "linda"},
	{"li-ndö", "li-ndjo", "li-ndO"},
	{"li-ndö-tî-sînga", "li-ndjo-tJi-sJinga", "li-ndO-TI-SInga"},
	{"li-ndö-tî-tokua", "li-ndjo-tJi-tokua", "li-ndO-TI-tokua"},
	{"lïngä", "ljingja", "lIngA"},
	{"lîngbi", "lJingbi", "LIngbi"},
	{"lîngbi", "lJingbi", "LIngbi"},
	{"lïngɔ̈", "ljingjc", "lIngC"},
	{"li-ngû", "li-ngJu", "li-NGU"},
	{"lîɔ", "lJic", "LIc"},
	{"lisoro", "lisoro", "lisoro"},
	{"li-tɛ̈nɛ̈", "li-tjxnjx", "li-tXnX"},
	{"li-tï", "li-tji", "li-tI"},
	{"li tî tûrûngu", "li tJi tJurJungu", "li TI TURUngu"},
	{"lo", "lo", "lo"},
	{"lö", "ljo", "lO"},
	{"lö-bîâ", "ljo-bJiJa", "lO-BIA"},
	{"lö-gbïä", "ljo-gbjija", "lO-gbIjA"},
	{"lɔkpɔtɔ", "lckpctc", "lckpctc"},
	{"lö-kûtu", "ljo-kJutu", "lO-KUtu"},
	{"lolo", "lolo", "lolo"},
	{"lɔ̈mbɔ̈", "ljcmbjc", "lCmbC"},
	{"lo mvɛnî", "lo mvxnJi", "lo mvxNI"},
	{"lö-ndâ", "ljo-ndJa", "lO-NDA"},
	{"löndö", "ljondjo", "lOndO"},
	{"löndö na", "ljondjo na", "lOndO na"},
	{"lɔngɔ", "lcngc", "lcngc"},
	{"lɔ̈rɔ̈", "ljcrjc", "lCrC"},
	{"lɔ̂sɔ", "lJcsc", "LCsc"},
	{"lü", "lju", "lU"},
	{"lungûla", "lungJula", "luNGUla"},
	{"lûpa", "lJupa", "LUpa"},
	{"lütï", "ljutji", "lUtI"},
	{"lûu", "lJuu", "LUu"},
	{"lûu", "lJuu", "LUu"},
	{"ma", "ma", "ma"},
	{"mâ", "mJa", "MA"},
	{"mä", "mja", "mA"},
	{"mabaya", "mabaya", "mabaya"},
	{"ma bɛ̂", "ma bJx", "ma BX"},
	{"ma-bɛ̂", "ma-bJx", "ma-BX"},
	{"mabɔ̂kɔ", "mabJckc", "maBCkc"},
	{"mafüta", "mafjuta", "mafUta"},
	{"mafüta tî mbûrü", "mafjuta tJi mbJurju", "mafUta TI MBUrU"},
	{"mafüta tî ngû tî mɛ tî bâgara", "mafjuta tJi ngJu tJi mx tJi bJagara", "mafUta TI NGU TI mx TI BAgara"},
	{"mafüta tî wɔ̂tɔrɔ", "mafjuta tJi wJctcrc", "mafUta TI WCtcrc"},
	{"magbɔ̈ngä", "magbjcngja", "magbCngA"},
	{"magia", "magia", "magia"},
	{"makâko", "makJako", "maKAko"},
	{"makala", "makala", "makala"},
	{"makângo", "makJango", "maKAngo"},
	{"makelâ", "makelJa", "makeLA"},
	{"makobe", "makobe", "makobe"},
	{"makongö", "makongjo", "makongO"},
	{"makoröo", "makorjoo", "makorOo"},
	{"malangi", "malangi", "malangi"},
	{"malînga", "malJinga", "maLInga"},
	{"mamâ", "mamJa", "maMA"},
	{"mamâ tî mâpa", "mamJa tJi mJapa", "maMA TI MApa"},
	{"mamîwätä", "mamJiwjatja", "maMIwAtA"},
	{"mä na bɛ̂", "mja na bJx", "mA na BX"},
	{"mä-na-bɛ̂", "mja-na-bJx", "mA-na-BX"},
	{"manda", "manda", "manda"},
	{"mä ndâ", "mja ndJa", "mA NDA"},
	{"mandako", "mandako", "mandako"},
	{"mändängɔ̈", "mjandjangjc", "mAndAngC"},
	{"mä-ndo", "mja-ndo", "mA-ndo"},
	{"mânga", "mJanga", "MAnga"},
	{"mangbɛ̂rɛ̂", "mangbJxrJx", "maNGBXRX"},
	{"mângbi", "mJangbi", "MAngbi"},
	{"mângbi", "mJangbi", "MAngbi"},
	{"mangbökö", "mangbjokjo", "mangbOkO"},
	{"mângo", "mJango", "MAngo"},
	{"manzêke", "manzJeke", "maNZEke"},
	{"manzinzi", "manzinzi", "manzinzi"},
	{"mâpa", "mJapa", "MApa"},
	{"mapîâ", "mapJiJa", "maPIA"},
	{"mapô", "mapJo", "maPO"},
	{"marä", "marja", "marA"},
	{"märä", "mjarja", "mArA"},
	{"masango", "masango", "masango"},
	{"mâsarâgba", "mJasarJagba", "MAsaRAgba"},
	{"maseka", "maseka", "maseka"},
	{"maseka tî kɔ̂lï", "maseka tJi kJclji", "maseka TI KClI"},
	{"maseka tî wâlï", "maseka tJi wJalji", "maseka TI WAlI"},
	{"masïni", "masjini", "masIni"},
	{"masua", "masua", "masua"},
	{"matabïsi", "matabjisi", "matabIsi"},
	{"matânga", "matJanga", "maTAnga"},
	{"mawa", "mawa", "mawa"},
	{"mawa", "mawa", "mawa"},
	{"mawôya", "mawJoya", "maWOya"},
	{"mä-yângâ", "mja-yJangJa", "mA-YANGA"},
	{"mayɛ̈rɛ", "mayjxrx", "mayXrx"},
	{"mbâ", "mbJa", "MBA"},
	{"mbadi", "mbadi", "mbadi"},
	{"mbâgë", "mbJagje", "MBAgE"},
	{"mbâgë tî kɔ̂lï", "mbJagje tJi kJclji", "MBAgE TI KClI"},
	{"mbâgë tî wâlï", "mbJagje tJi wJalji", "MBAgE TI WAlI"},
	{"mbai", "mbai", "mbai"},
	{"mbâkêlê", "mbJakJelJe", "MBAKELE"},
	{"mbäkɔ̂rɔ", "mbjakJcrc", "mbAKCrc"},
	{"mbäkɔ̂rɔ", "mbjakJcrc", "mbAKCrc"},
	{"mbala", "mbala", "mbala"},
	{"mbamba", "mbamba", "mbamba"},
	{"mbamba", "mbamba", "mbamba"},
	{"mbänä", "mbjanja", "mbAnA"},
	{"mbängü", "mbjangju", "mbAngU"},
	{"mbanu", "mbanu", "mbanu"},
	{"mbârâmbârâ", "mbJarJambJarJa", "MBARAMBARA"},
	{"mbârâmbârâ", "mbJarJambJarJa", "MBARAMBARA"},
	{"mbârâtâ", "mbJarJatJa", "MBARATA"},
	{"mbârâwârâ", "mbJarJawJarJa", "MBARAWARA"},
	{"mbâsa", "mbJasa", "MBAsa"},
	{"mbâsala", "mbJasala", "MBAsala"},
	{"mbâsâmbârâ", "mbJasJambJarJa", "MBASAMBARA"},
	{"mbâsâmbârâ", "mbJasJambJarJa", "MBASAMBARA"},
	{"mbata", "mbata", "mbata"},
	{"mbätä", "mbjatja", "mbAtA"},
	{"mbɛ̂â", "mbJxJa", "MBXA"},
	{"mbɛ̈ngɛ̈", "mbjxngjx", "mbXngX"},
	{"mbɛ̈ngɛ̈", "mbjxngjx", "mbXngX"},
	{"mbɛ̂nî", "mbJxnJi", "MBXNI"},
	{"mbɛ̂nî", "mbJxnJi", "MBXNI"},
	{"mbɛ̂nî", "mbJxnJi", "MBXNI"},
	{"mbɛ̂nî äpɛ", "mbJxnJi japx", "MBXNI jApx"},
	{"mbɛ̂nî-bîrï", "mbJxnJi-bJirji", "MBXNI-BIrI"},
	{"mbɛ̂nî-kêkerêke", "mbJxnJi-kJekerJeke", "MBXNI-KEkeREke"},
	{"mbɛ̂nî-lâ", "mbJxnJi-lJa", "MBXNI-LA"},
	{"mbɛ̂nî pɛ̈pɛ", "mbJxnJi pjxpx", "MBXNI pXpx"},
	{"mbere", "mbere", "mbere"},
	{"mbere", "mbere", "mbere"},
	{"mbɛ̂rɛ̂kɛ̂", "mbJxrJxkJx", "MBXRXKX"},
	{"mbeso", "mbeso", "mbeso"},
	{"mbɛ̈tï", "mbjxtji", "mbXtI"},
	{"mbɛ̈tï-kua", "mbjxtji-kua", "mbXtI-kua"},
	{"mbɛ̈tï-lêgë", "mbjxtji-lJegje", "mbXtI-LEgE"},
	{"mbɛ̈tï-sango", "mbjxtji-sango", "mbXtI-sango"},
	{"mbɛ̈tï tî nzapä", "mbjxtji tJi nzapja", "mbXtI TI nzapA"},
	{"mbɛ̈tï-tokua", "mbjxtji-tokua", "mbXtI-tokua"},
	{"mbɛtɔ", "mbxtc", "mbxtc"},
	{"mbï", "mbji", "mbI"},
	{"mbï mvɛnî", "mbji mvxnJi", "mbI mvxNI"},
	{"mbîndä", "mbJindja", "MBIndA"},
	{"mbîngo", "mbJingo", "MBIngo"},
	{"mbïɔ̈", "mbjijc", "mbIjC"},
	{"mbîrîmbîrî", "mbJirJimbJirJi", "MBIRIMBIRI"},
	{"mbîrîmbîrî", "mbJirJimbJirJi", "MBIRIMBIRI"},
	{"mbo", "mbo", "mbo"},
	{"mbô", "mbJo", "MBO"},
	{"mbö", "mbjo", "mbO"},
	{"mbôko", "mbJoko", "MBOko"},
	{"mbôko", "mbJoko", "MBOko"},
	{"mbôko-li", "mbJoko-li", "MBOko-li"},
	{"mbɔ̈kɔ̂rɔ", "mbjckJcrc", "mbCKCrc"},
	{"mbômbô", "mbJombJo", "MBOMBO"},
	{"mbômbô-li", "mbJombJo-li", "MBOMBO-li"},
	{"mbongo", "mbongo", "mbongo"},
	{"mböngɔ̈", "mbjongjc", "mbOngC"},
	{"mbɔ̂ngɔ", "mbJcngc", "MBCngc"},
	{"mborô", "mborJo", "mboRO"},
	{"mbôrôrô", "mbJorJorJo", "MBORORO"},
	{"mbɔtɔ̈", "mbctjc", "mbctC"},
	{"mbûki", "mbJuki", "MBUki"},
	{"mbuma", "mbuma", "mbuma"},
	{"mburu", "mburu", "mburu"},
	{"mbûrü", "mbJurju", "MBUrU"},
	{"mburu tî wâ", "mburu tJi wJa", "mburu TI WA"},
	{"mburu tî wâ", "mburu tJi wJa", "mburu TI WA"},
	{"mbütü", "mbjutju", "mbUtU"},
	{"mɛ", "mx", "mx"},
	{"mɛ", "mx", "mx"},
	{"mɛ̂", "mJx", "MX"},
	{"mɛ̂", "mJx", "MX"},
	{"mêa", "mJea", "MEa"},
	{"mɛɛ̈", "mxjx", "mxjX"},
	{"mɛka", "mxka", "mxka"},
	{"mɛka", "mxka", "mxka"},
	{"mɛnɛ", "mxnx", "mxnx"},
	{"mɛ̂nɛ̈", "mJxnjx", "MXnX"},
	{"mɛ̈ngä", "mjxngja", "mXngA"},
	{"mɛ̈ngɔ̈", "mjxngjc", "mXngC"},
	{"mɛ̂sa", "mJxsa", "MXsa"},
	{"mɛtï", "mxtji", "mxtI"},
	{"mî", "mJi", "MI"},
	{"mîmi", "mJimi", "MImi"},
	{"mîngi", "mJingi", "MIngi"},
	{"mîngi", "mJingi", "MIngi"},
	{"mîngɔ", "mJingc", "MIngc"},
	{"miɔmbe", "micmbe", "micmbe"},
	{"miɔmbe", "micmbe", "micmbe"},
	{"mî-suïya", "mJi-sujiya", "MI-sujIya"},
	{"mî-tɛrɛ̂", "mJi-txrJx", "MI-txRX"},
	{"mɔ", "mc", "mc"},
	{"mɔ-bâa-mɔ-tɛnɛ", "mc-bJaa-mc-txnx", "mc-BAa-mc-txnx"},
	{"mɔ-yê-tî-bâa", "mc-yJe-tJi-bJaa", "mc-YE-TI-BAa"},
	{"mɔbangë", "mcbangje", "mcbangE"},
	{"mɔdɔ̈gɛrɛ̂", "mcdjcgxrJx", "mcdCgxRX"},
	{"mɔkiri", "mckiri", "mckiri"},
	{"mɔkondö", "mckondjo", "mckondO"},
	{"mɔkondö", "mckondjo", "mckondO"},
	{"mokönzi", "mokjonzi", "mokOnzi"},
	{"môlɛngɛ̂", "mJolxngJx", "MOlxNGX"},
	{"môlɛngɛ̂", "mJolxngJx", "MOlxNGX"},
	{"môlɛngɛ̂", "mJolxngJx", "MOlxNGX"},
	{"môlɛngɛ̂ tî kɔ̂lï", "mJolxngJx tJi kJclji", "MOlxNGX TI KClI"},
	{"môlɛngɛ̂ tî ndeko", "mJolxngJx tJi ndeko", "MOlxNGX TI ndeko"},
	{"môlɛngɛ̂ tî wâlï", "mJolxngJx tJi wJalji", "MOlxNGX TI WAlI"},
	{"molongö", "molongjo", "molongO"},
	{"mɔ mvɛnî", "mc mvxnJi", "mc mvxNI"},
	{"mondelepâko", "mondelepJako", "mondelePAko"},
	{"mongânga", "mongJanga", "moNGAnga"},
	{"möngö-li", "mjongjo-li", "mOngO-li"},
	{"mopɛpɛ", "mopxpx", "mopxpx"},
	{"mɔpï", "mcpji", "mcpI"},
	{"mɔsasako", "mcsasako", "mcsasako"},
	{"mosongôli", "mosongJoli", "mosoNGOli"},
	{"mɔsɔrɔ", "mcscrc", "mcscrc"},
	{"mosümä", "mosjumja", "mosUmA"},
	{"mɔzïngɔ̈", "mczjingjc", "mczIngC"},
	{"mû", "mJu", "MU"},
	{"müä", "mjuja", "mUjA"},
	{"muen", "muen", "mueN"},
	{"mû kɔ̂lï", "mJu kJclji", "MU KClI"},
	{"mû lêgë", "mJu lJegje", "MU LEgE"},
	{"mû lêgë na", "mJu lJegje na", "MU LEgE na"},
	{"mûlu", "mJulu", "MUlu"},
	{"mû mabɔ̂kɔ na", "mJu mabJckc na", "MU maBCkc na"},
	{"mû na mbï", "mJu na mbji", "MU na mbI"},
	{"mûngbi", "mJungbi", "MUngbi"},
	{"mûngbi", "mJungbi", "MUngbi"},
	{"mû ngîâ na bɛ̂ tî", "mJu ngJiJa na bJx tJi", "MU NGIA na BX TI"},
	{"munzû", "munzJu", "muNZU"},
	{"munzû-nzapä", "munzJu-nzapja", "muNZU-nzapA"},
	{"munzû-vukɔ̈", "munzJu-vukjc", "muNZU-vukC"},
	{"mûrû", "mJurJu", "MURU"},
	{"mû wâ", "mJu wJa", "MU WA"},
	{"mû wâlï", "mJu wJalji", "MU WAlI"},
	{"mû wängɔ̈", "mJu wjangjc", "MU wAngC"},
	{"mû wängɔ̈ na", "mJu wjangjc na", "MU wAngC na"},
	{"mû yângâ tî", "mJu yJangJa tJi", "MU YANGA TI"},
	{"mvɛlɛ", "mvxlx", "mvxlx"},
	{"mvɛnɛ", "mvxnx", "mvxnx"},
	{"mvɛnɛ", "mvxnx", "mvxnx"},
	{"mvɛnî", "mvxnJi", "mvxNI"},
	{"mvitasiöon", "mvitasijoon", "mvitasijOoN"},
	{"mvüka", "mvjuka", "mvUka"},
	{"na", "na", "na"},
	{"na", "na", "na"},
	{"nabändurü", "nabjandurju", "nabAndurU"},
	{"na mbâgë wa", "na mbJagje wa", "na MBAgE wa"},
	{"na ndo wa", "na ndo wa", "na ndo wa"},
	{"ndâ", "ndJa", "NDA"},
	{"ndâ-gɛrɛ̂", "ndJa-gxrJx", "NDA-gxRX"},
	{"ndâ-li", "ndJa-li", "NDA-li"},
	{"ndâ-li", "ndJa-li", "NDA-li"},
	{"ndâ-li tî", "ndJa-li tJi", "NDA-li TI"},
	{"ndâ-li tî nyɛ", "ndJa-li tJi nyx", "NDA-li TI nyx"},
	{"ndâ-li tî sô", "ndJa-li tJi sJo", "NDA-li TI SO"},
	{"ndâ-li tî sô", "ndJa-li tJi sJo", "NDA-li TI SO"},
	{"ndâ-lö", "ndJa-ljo", "NDA-lO"},
	{"ndâmbo", "ndJambo", "NDAmbo"},
	{"ndângbâ", "ndJangbJa", "NDANGBA"},
	{"ndângbâ-li-tï", "ndJangbJa-li-tji", "NDANGBA-li-tI"},
	{"ndao", "ndao", "ndao"},
	{"ndäpêrê", "ndjapJerJe", "ndAPERE"},
	{"ndäpêrêrê", "ndjapJerJerJe", "ndAPERERE"},
	{"ndarä", "ndarja", "ndarA"},
	{"ndârâ", "ndJarJa", "NDARA"},
	{"ndaramba", "ndaramba", "ndaramba"},
	{"ndatu", "ndatu", "ndatu"},
	{"ndaü", "ndaju", "ndajU"},
	{"ndê", "ndJe", "NDE"},
	{"ndê", "ndJe", "NDE"},
	{"ndɛkɛ", "ndxkx", "ndxkx"},
	{"ndeko", "ndeko", "ndeko"},
	{"ndeko-zändë", "ndeko-zjandje", "ndeko-zAndE"},
	{"ndembë", "ndembje", "ndembE"},
	{"ndembö", "ndembjo", "ndembO"},
	{"ndê-ndê", "ndJe-ndJe", "NDE-NDE"},
	{"ndê-ndê", "ndJe-ndJe", "NDE-NDE"},
	{"ndiba", "ndiba", "ndiba"},
	{"ndikâ", "ndikJa", "ndiKA"},
	{"ndindïä", "ndindjija", "ndindIjA"},
	{"ndïrï", "ndjirji", "ndIrI"},
	{"ndo", "ndo", "ndo"},
	{"ndô", "ndJo", "NDO"},
	{"ndö", "ndjo", "ndO"},
	{"ndoï", "ndoji", "ndojI"},
	{"ndɔ̈kɔ̈", "ndjckjc", "ndCkC"},
	{"ndɔkɔ̂rɔ̈", "ndckJcrjc", "ndcKCrC"},
	{"ndö-lɛ̂", "ndjo-lJx", "ndO-LX"},
	{"ndɔmbɛ", "ndcmbx", "ndcmbx"},
	{"ndɔmbɔ̈", "ndcmbjc", "ndcmbC"},
	{"ndôngô", "ndJongJo", "NDONGO"},
	{"ndö-nî", "ndjo-nJi", "ndO-NI"},
	{"ndôo", "ndJoo", "NDOo"},
	{"ndö-tî", "ndjo-tJi", "ndO-TI"},
	{"ndo-wâ", "ndo-wJa", "ndo-WA"},
	{"ndö-yê", "ndjo-yJe", "ndO-YE"},
	{"ndö-yê", "ndjo-yJe", "ndO-YE"},
	{"ndö-yëngɔ̈", "ndjo-yjengjc", "ndO-yEngC"},
	{"ndö-yëngɔ̈", "ndjo-yjengjc", "ndO-yEngC"},
	{"ndû", "ndJu", "NDU"},
	{"ndü", "ndju", "ndU"},
	{"ndûmba", "ndJumba", "NDUmba"},
	{"ndurü", "ndurju", "ndurU"},
	{"ndûrûkpâ", "ndJurJukpJa", "NDURUKPA"},
	{"ndütü", "ndjutju", "ndUtU"},
	{"ndüzü", "ndjuzju", "ndUzU"},
	{"nɛ", "nx", "nx"},
	{"nɛka", "nxka", "nxka"},
	{"nɛ̈ngɔ̈", "njxngjc", "nXngC"},
	{"ngâ", "ngJa", "NGA"},
	{"ngä", "ngja", "ngA"},
	{"ngâakôo", "ngJaakJoo", "NGAaKOo"},
	{"ngâgö", "ngJagjo", "NGAgO"},
	{"ngambi", "ngambi", "ngambi"},
	{"ngän", "ngjan", "ngAN"},
	{"nganga", "nganga", "nganga"},
	{"ngängä", "ngjangja", "ngAngA"},
	{"ngango", "ngango", "ngango"},
	{"ngangü", "ngangju", "ngangU"},
	{"ngangü", "ngangju", "ngangU"},
	{"ngangü", "ngangju", "ngangU"},
	{"ngâo", "ngJao", "NGAo"},
	{"ngâo", "ngJao", "NGAo"},
	{"ngâpô", "ngJapJo", "NGAPO"},
	{"ngäsa", "ngjasa", "ngAsa"},
	{"ngâsî", "ngJasJi", "NGASI"},
	{"ngbâ", "ngbJa", "NGBA"},
	{"ngbä", "ngbja", "ngbA"},
	{"ngbâa", "ngbJaa", "NGBAa"},
	{"ngbadârâ", "ngbadJarJa", "ngbaDARA"},
	{"ngbâko", "ngbJako", "NGBAko"},
	{"ngbâ-kongö", "ngbJa-kongjo", "NGBA-kongO"},
	{"ngbâlo", "ngbJalo", "NGBAlo"},
	{"ngbanga", "ngbanga", "ngbanga"},
	{"ngbanga tî", "ngbanga tJi", "ngbanga TI"},
	{"ngbanga tî nyɛ", "ngbanga tJi nyx", "ngbanga TI nyx"},
	{"ngbanga tî sô", "ngbanga tJi sJo", "ngbanga TI SO"},
	{"ngbanga tî sô", "ngbanga tJi sJo", "ngbanga TI SO"},
	{"ngbângbä", "ngbJangbja", "NGBAngbA"},
	{"ngbängbâ", "ngbjangbJa", "ngbANGBA"},
	{"ngbangbo", "ngbangbo", "ngbangbo"},
	{"ngbangbo", "ngbangbo", "ngbangbo"},
	{"ngbangbo-", "ngbangbo-", "ngbangbo-"},
	{"ngbangbo-tukîa", "ngbangbo-tukJia", "ngbangbo-tuKIa"},
	{"ngbângêrêngû", "ngbJangJerJengJu", "NGBANGERENGU"},
	{"ngbängɔ̈", "ngbjangjc", "ngbAngC"},
	{"ngbâ nzɔ̈nî", "ngbJa nzjcnJi", "NGBA nzCNI"},
	{"ngbɛ̂nɛ", "ngbJxnx", "NGBXnx"},
	{"ngbëngbë", "ngbjengbje", "ngbEngbE"},
	{"ngbengë", "ngbengje", "ngbengE"},
	{"ngbêrênâ", "ngbJerJenJa", "NGBERENA"},
	{"ngbɛrɛrɛ", "ngbxrxrx", "ngbxrxrx"},
	{"ngbiii", "ngbiii", "ngbiii"},
	{"ngbiii asî na", "ngbiii asJi na", "ngbiii aSI na"},
	{"ngbiii sï", "ngbiii sji", "ngbiii sI"},
	{"ngbɔ̈", "ngbjc", "ngbC"},
	{"ngbɔ̈", "ngbjc", "ngbC"},
	{"ngbɔ̈kɔ̈", "ngbjckjc", "ngbCkC"},
	{"ngbondä", "ngbondja", "ngbondA"},
	{"ngbondô", "ngbondJo", "ngboNDO"},
	{"ngbonga", "ngbonga", "ngbonga"},
	{"ngbonga", "ngbonga", "ngbonga"},
	{"ngbongbôro", "ngbongbJoro", "ngboNGBOro"},
	{"ngbɔngbɔ̈rɔ̈", "ngbcngbjcrjc", "ngbcngbCrC"},
	{"ngbongboto", "ngbongboto", "ngbongboto"},
	{"ngbɔ̂ngɔ̂", "ngbJcngJc", "NGBCNGC"},
	{"ngbôto", "ngbJoto", "NGBOto"},
	{"ngbûku", "ngbJuku", "NGBUku"},
	{"ngbundangbu", "ngbundangbu", "ngbundangbu"},
	{"ngbundangbu", "ngbundangbu", "ngbundangbu"},
	{"ngbundangbu-", "ngbundangbu-", "ngbundangbu-"},
	{"ngbungbu", "ngbungbu", "ngbungbu"},
	{"ngbuta", "ngbuta", "ngbuta"},
	{"ngɛ", "ngx", "ngx"},
	{"ngɛ", "ngx", "ngx"},
	{"ngɛndɛ̈", "ngxndjx", "ngxndX"},
	{"ngenge", "ngenge", "ngenge"},
	{"ngɛ̈ngɔ̈", "ngjxngjc", "ngXngC"},
	{"ngêrë", "ngJerje", "NGErE"},
	{"ngîâ", "ngJiJa", "NGIA"},
	{"ngiba", "ngiba", "ngiba"},
	{"nginza", "nginza", "nginza"},
	{"ngira", "ngira", "ngira"},
	{"ngiriba", "ngiriba", "ngiriba"},
	{"ngïrïkï", "ngjirjikji", "ngIrIkI"},
	{"ngo", "ngo", "ngo"},
	{"ngô", "ngJo", "NGO"},
	{"ngɔ", "ngc", "ngc"},
	{"ngɔ", "ngc", "ngc"},
	{"ngɔ̈", "ngjc", "ngC"},
	{"ngɔ̈", "ngjc", "ngC"},
	{"ngoi", "ngoi", "ngoi"},
	{"ngoi tî burü", "ngoi tJi burju", "ngoi TI burU"},
	{"ngoi tî ngû", "ngoi tJi ngJu", "ngoi TI NGU"},
	{"ngɔ̂lɔ̈", "ngJcljc", "NGClC"},
	{"ngɔ̈lɔ", "ngjclc", "ngClc"},
	{"ngombe", "ngombe", "ngombe"},
	{"ngonda", "ngonda", "ngonda"},
	{"ngonga", "ngonga", "ngonga"},
	{"ngôngbi", "ngJongbi", "NGOngbi"},
	{"ngôngbi", "ngJongbi", "NGOngbi"},
	{"ngonzâ", "ngonzJa", "ngoNZA"},
	{"ngɔnzɔ", "ngcnzc", "ngcnzc"},
	{"ngoro", "ngoro", "ngoro"},
	{"ngɔrɔ", "ngcrc", "ngcrc"},
	{"ngôrôngbi", "ngJorJongbi", "NGOROngbi"},
	{"ngöröngbö", "ngjorjongbjo", "ngOrOngbO"},
	{"ngoropangi", "ngoropangi", "ngoropangi"},
	{"ngo-tï", "ngo-tji", "ngo-tI"},
	{"ngû", "ngJu", "NGU"},
	{"nguba", "nguba", "nguba"},
	{"ngubë", "ngubje", "ngubE"},
	{"ngubü", "ngubju", "ngubU"},
	{"ngui", "ngui", "ngui"},
	{"ngû-îngɔ̈", "ngJu-Jingjc", "NGU-IngC"},
	{"ngû-lavu", "ngJu-lavu", "NGU-lavu"},
	{"ngû-lɛ̂", "ngJu-lJx", "NGU-LX"},
	{"ngûmbâ", "ngJumbJa", "NGUMBA"},
	{"ngumu", "ngumu", "ngumu"},
	{"ngundë", "ngundje", "ngundE"},
	{"ngungu", "ngungu", "ngungu"},
	{"ngû-ngunzä", "ngJu-ngunzja", "NGU-ngunzA"},
	{"ngunzä", "ngunzja", "ngunzA"},
	{"ngû-nzapä", "ngJu-nzapja", "NGU-nzapA"},
	{"ngûnzapä", "ngJunzapja", "NGUnzapA"},
	{"ngûru", "ngJuru", "NGUru"},
	{"ngusü", "ngusju", "ngusU"},
	{"ngû tî kɔ̂lï", "ngJu tJi kJclji", "NGU TI KClI"},
	{"ngû tî lɛ̂", "ngJu tJi lJx", "NGU TI LX"},
	{"ngû tî mbɛ̈tï", "ngJu tJi mbjxtji", "NGU TI mbXtI"},
	{"ngû tî mɛ", "ngJu tJi mx", "NGU TI mx"},
	{"ngû tî mɛ tî bâgara", "ngJu tJi mx tJi bJagara", "NGU TI mx TI BAgara"},
	{"ngû tî nyön", "ngJu tJi nyjon", "NGU TI nyON"},
	{"ngû tî nzapä", "ngJu tJi nzapja", "NGU TI nzapA"},
	{"ngû tî tɛrɛ̂", "ngJu tJi txrJx", "NGU TI txRX"},
	{"ngû tî vurü", "ngJu tJi vurju", "NGU TI vurU"},
	{"ngû tî yängâ", "ngJu tJi yjangJa", "NGU TI yANGA"},
	{"ngû-yenga", "ngJu-yenga", "NGU-yenga"},
	{"nî", "nJi", "NI"},
	{"nî", "nJi", "NI"},
	{"nï", "nji", "nI"},
	{"nîgisi", "nJigisi", "NIgisi"},
	{"nika", "nika", "nika"},
	{"nïkpä", "njikpja", "nIkpA"},
	{"nînga", "nJinga", "NInga"},
	{"nô", "nJo", "NO"},
	{"nö", "njo", "nO"},
	{"nɔ̈kɔ̈", "njckjc", "nCkC"},
	{"nyama", "nyama", "nyama"},
	{"nyâu", "nyJau", "NYAu"},
	{"nyɛ", "nyx", "nyx"},
	{"nyɛnɛ̈", "nyxnjx", "nyxnX"},
	{"nyɛngo", "nyxngo", "nyxngo"},
	{"nyɛnyɛ", "nyxnyx", "nyxnyx"},
	{"nyɛnyɛkɛ̂", "nyxnyxkJx", "nyxnyxKX"},
	{"nyï", "nyji", "nyI"},
	{"nyï-kɛ̂lï", "nyji-kJxlji", "nyI-KXlI"},
	{"nyï-li-tï", "nyji-li-tji", "nyI-li-tI"},
	{"nyï-ndü", "nyji-ndju", "nyI-ndU"},
	{"nyï-ngambi", "nyji-ngambi", "nyI-ngambi"},
	{"nyï-wâlï", "nyji-wJalji", "nyI-WAlI"},
	{"nyï-wanda", "nyji-wanda", "nyI-wanda"},
	{"nyɔ̈n", "nyjcn", "nyCN"},
	{"nyɔ̈n mânga", "nyjcn mJanga", "nyCN MAnga"},
	{"nyɔ̈n mɛ̂nɛ̈", "nyjcn mJxnjx", "nyCN MXnX"},
	{"nza", "nza", "nza"},
	{"nzä", "nzja", "nzA"},
	{"nzabï", "nzabji", "nzabI"},
	{"nzaï", "nzaji", "nzajI"},
	{"nzângi", "nzJangi", "NZAngi"},
	{"nzanza", "nzanza", "nzanza"},
	{"nzanzë", "nzanzje", "nzanzE"},
	{"nzapä", "nzapja", "nzapA"},
	{"nzapä", "nzapja", "nzapA"},
	{"nzapä-babâ", "nzapja-babJa", "nzapA-baBA"},
	{"nzara", "nzara", "nzara"},
	{"nzara tî ngû", "nzara tJi ngJu", "nzara TI NGU"},
	{"nzayü", "nzayju", "nzayU"},
	{"nzɛ", "nzx", "nzx"},
	{"nzɛ", "nzx", "nzx"},
	{"nzɛ", "nzx", "nzx"},
	{"nzɛ balë-ɔ̂kɔ", "nzx balje-Jckc", "nzx balE-Ckc"},
	{"nzɛ balë-ɔ̂kɔ na ɔ̂kɔ", "nzx balje-Jckc na Jckc", "nzx balE-Ckc na Ckc"},
	{"nzɛ balë-ɔ̂kɔ na ûse", "nzx balje-Jckc na Juse", "nzx balE-Ckc na Use"},
	{"nzêen", "nzJeen", "NZEeN"},
	{"nzêen na pekö tî", "nzJeen na pekjo tJi", "NZEeN na pekO TI"},
	{"nzëgë", "nzjegje", "nzEgE"},
	{"nzɛli", "nzxli", "nzxli"},
	{"nzɛ mbârâmbârâ", "nzx mbJarJambJarJa", "nzx MBARAMBARA"},
	{"nzɛ miɔmbe", "nzx micmbe", "nzx micmbe"},
	{"nzɛ̂nɛ", "nzJxnx", "NZXnx"},
	{"nzɛ̈nɛ̈", "nzjxnjx", "nzXnX"},
	{"nzɛ ngümbâyä", "nzx ngjumbJayja", "nzx ngUMBAyA"},
	{"nzɛnzɛ", "nzxnzx", "nzxnzx"},
	{"nzɛ ɔ̂kɔ", "nzx Jckc", "nzx Ckc"},
	{"nzɛ ɔkü", "nzx ckju", "nzx ckU"},
	{"nzɛ omɛnë", "nzx omxnje", "nzx omxnE"},
	{"nzɛ otâ", "nzx otJa", "nzx oTA"},
	{"nzêpêrê", "nzJepJerJe", "NZEPERE"},
	{"nzerë", "nzerje", "nzerE"},
	{"nzɛrɛ", "nzxrx", "nzxrx"},
	{"nzɛrɛ na bɛ̂ tî", "nzxrx na bJx tJi", "nzxrx na BX TI"},
	{"nzɛ̈rɛ̈ngɔ̈", "nzjxrjxngjc", "nzXrXngC"},
	{"nzɛ̈rɛ̈ngɔ̈", "nzjxrjxngjc", "nzXrXngC"},
	{"nzerë tî ndüzü", "nzerje tJi ndjuzju", "nzerE TI ndUzU"},
	{"nzerë-tî-yê", "nzerje-tJi-yJe", "nzerE-TI-YE"},
	{"nzɛ ûse", "nzx Juse", "nzx Use"},
	{"nzɛ usïö", "nzx usjijo", "nzx usIjO"},
	{"nzï", "nzji", "nzI"},
	{"nzîna-", "nzJina-", "NZIna-"},
	{"nzîna-ngonga", "nzJina-ngonga", "NZIna-ngonga"},
	{"nzïngɔ̈", "nzjingjc", "nzIngC"},
	{"nzɔ̈", "nzjc", "nzC"},
	{"nzɔ̈-", "nzjc-", "nzC-"},
	{"nzɔ̈-bä", "nzjc-bja", "nzC-bA"},
	{"nzɔ̈-bê", "nzjc-bJe", "nzC-BE"},
	{"nzɔ̈-bîâ", "nzjc-bJiJa", "nzC-BIA"},
	{"nzɔ̈-dëbä", "nzjc-djebja", "nzC-dEbA"},
	{"nzɔmbɔ̈", "nzcmbjc", "nzcmbC"},
	{"nzɔ̈ngɔ̈rɔ̈", "nzjcngjcrjc", "nzCngCrC"},
	{"nzɔ̈nî", "nzjcnJi", "nzCNI"},
	{"nzɔ̈nî", "nzjcnJi", "nzCNI"},
	{"nzɔ̈nî", "nzjcnJi", "nzCNI"},
	{"nzɔ̈nî-sango", "nzjcnJi-sango", "nzCNI-sango"},
	{"nzɔrɔ̂kɔ", "nzcrJckc", "nzcRCkc"},
	{"nzɔrɔ̂kɔ", "nzcrJckc", "nzcRCkc"},
	{"nzɔrɔ̂kɔ", "nzcrJckc", "nzcRCkc"},
	{"nzɔrɔ̂kɔ kömbë", "nzcrJckc kjombje", "nzcRCkc kOmbE"},
	{"nzɔ̈-sango", "nzjc-sango", "nzC-sango"},
	{"o", "o", "o"},
	{"o", "o", "o"},
	{"ɔ̂kɛ", "Jckx", "Ckx"},
	{"ɔ̂kɔ", "Jckc", "Ckc"},
	{"ɔ̂kɔ", "Jckc", "Ckc"},
	{"ɔ̂kɔ äpɛ", "Jckc japx", "Ckc jApx"},
	{"ɔ̂kɔ äpɛ", "Jckc japx", "Ckc jApx"},
	{"ɔ̂kɔ-ɔ̂kɔ", "Jckc-Jckc", "Ckc-Ckc"},
	{"ɔ̂kɔ pɛ̈pɛ", "Jckc pjxpx", "Ckc pXpx"},
	{"ɔ̂kɔ pɛ̈pɛ", "Jckc pjxpx", "Ckc pXpx"},
	{"ɔkü", "ckju", "ckU"},
	{"ɔkü", "ckju", "ckU"},
	{"omɛnë", "omxnje", "omxnE"},
	{"omɛnë", "omxnje", "omxnE"},
	{"otâ", "otJa", "oTA"},
	{"otâ", "otJa", "oTA"},
	{"ɔ̂tɔ̈", "Jctjc", "CtC"},
	{"pâ", "pJa", "PA"},
	{"pä", "pja", "pA"},
	{"pâ-fungûla", "pJa-fungJula", "PA-fuNGUla"},
	{"pä ïrï tî", "pja jirji tJi", "pA jIrI TI"},
	{"pakapâka", "pakapJaka", "pakaPAka"},
	{"pakara", "pakara", "pakara"},
	{"pambo", "pambo", "pambo"},
	{"pâmbo-tï", "pJambo-tji", "PAmbo-tI"},
	{"pandë", "pandje", "pandE"},
	{"pängä", "pjangja", "pAngA"},
	{"papa", "papa", "papa"},
	{"papa", "papa", "papa"},
	{"pâpa", "pJapa", "PApa"},
	{"pâpâ", "pJapJa", "PAPA"},
	{"papayë", "papayje", "papayE"},
	{"pärä", "pjarja", "pArA"},
	{"pärä", "pjarja", "pArA"},
	{"pärä-gɛrɛ̈", "pjarja-gxrjx", "pArA-gxrX"},
	{"pärä-tï", "pjarja-tji", "pArA-tI"},
	{"päsä", "pjasja", "pAsA"},
	{"päsäpɔ̂rɔ", "pjasjapJcrc", "pAsAPCrc"},
	{"pasëe", "pasjee", "pasEe"},
	{"pâsi", "pJasi", "PAsi"},
	{"pastɛ̈rɛ", "pastjxrx", "pastXrx"},
	{"patâ", "patJa", "paTA"},
	{"pâta", "pJata", "PAta"},
	{"patärä", "patjarja", "patArA"},
	{"pe", "pe", "pe"},
	{"pɛ̈", "pjx", "pX"},
	{"pɛkɛ̈", "pxkjx", "pxkX"},
	{"pekô", "pekJo", "peKO"},
	{"pekö", "pekjo", "pekO"},
	{"pekö", "pekjo", "pekO"},
	{"pekö", "pekjo", "pekO"},
	{"pekönî", "pekjonJi", "pekONI"},
	{"pɛ̈mbɛ̈", "pjxmbjx", "pXmbX"},
	{"pendä", "pendja", "pendA"},
	{"pɛndɛrɛ", "pxndxrx", "pxndxrx"},
	{"pɛndɛrɛ kɔ̂lï", "pxndxrx kJclji", "pxndxrx KClI"},
	{"pɛndɛrɛ wâlï", "pxndxrx wJalji", "pxndxrx WAlI"},
	{"pɛ̈ngɔ̈", "pjxngjc", "pXngC"},
	{"pɛnzɛ", "pxnzx", "pxnzx"},
	{"pɛ̈pɛ", "pjxpx", "pXpx"},
	{"pêrë", "pJerje", "PErE"},
	{"pɛtɛ", "pxtx", "pxtx"},
	{"pɛ̂tɛ", "pJxtx", "PXtx"},
	{"pɛ̈tɛ̈", "pjxtjx", "pXtX"},
	{"pîda", "pJida", "PIda"},
	{"pîka", "pJika", "PIka"},
	{"pîka-hôn", "pJika-hJon", "PIka-HON"},
	{"pîka kpêkê na", "pJika kpJekJe na", "PIka KPEKE na"},
	{"pîka kpêkê-ûse na", "pJika kpJekJe-Juse na", "PIka KPEKE-Use na"},
	{"pîka mabɔ̂kɔ", "pJika mabJckc", "PIka maBCkc"},
	{"pîka mbɛ̈tï", "pJika mbjxtji", "PIka mbXtI"},
	{"pîka ndembö", "pJika ndembjo", "PIka ndembO"},
	{"pîka-ngâsî", "pJika-ngJasJi", "PIka-NGASI"},
	{"pîka ngombe", "pJika ngombe", "PIka ngombe"},
	{"pîka ngû", "pJika ngJu", "PIka NGU"},
	{"pîka patärä", "pJika patjarja", "PIka patArA"},
	{"pîka patärä", "pJika patjarja", "PIka patArA"},
	{"pîka wên", "pJika wJen", "PIka WEN"},
	{"pilipîli", "pilipJili", "piliPIli"},
	{"pïndïrï", "pjindjirji", "pIndIrI"},
	{"pïndïrï tî wâ", "pjindjirji tJi wJa", "pIndIrI TI WA"},
	{"pîpï", "pJipji", "PIpI"},
	{"pîri", "pJiri", "PIri"},
	{"pito", "pito", "pito"},
	{"plâta", "plJata", "PLAta"},
	{"polêlê", "polJelJe", "poLELE"},
	{"polîsi", "polJisi", "poLIsi"},
	{"pɔ̈mɛ̈", "pjcmjx", "pCmX"},
	{"pɔ̂me-sitɛ̈rɛ", "pJcme-sitjxrx", "PCme-sitXrx"},
	{"pɔ̈mɛ̈tɛ̂rɛ", "pjcmjxtJxrx", "pCmXTXrx"},
	{"pɔngi", "pcngi", "pcngi"},
	{"pɔ̈ngï", "pjcngji", "pCngI"},
	{"pɔnɔ̈", "pcnjc", "pcnC"},
	{"popô", "popJo", "poPO"},
	{"popö", "popjo", "popO"},
	{"pöpö", "pjopjo", "pOpO"},
	{"pöpö-", "pjopjo-", "pOpO-"},
	{"pôpôrô", "pJopJorJo", "POPORO"},
	{"pɔ̈rɔ̈", "pjcrjc", "pCrC"},
	{"pɔ̈rɔ̈-lɛ̈", "pjcrjc-ljx", "pCrC-lX"},
	{"pɔ̈rɔ̈ tî gɛrɛ̂", "pjcrjc tJi gxrJx", "pCrC TI gxRX"},
	{"pɔ̈rɔ̈ tî kɛ̈kɛ̈", "pjcrjc tJi kjxkjx", "pCrC TI kXkX"},
	{"pɔ̈rɔ̈ tî mabɔ̂kɔ", "pjcrjc tJi mabJckc", "pCrC TI maBCkc"},
	{"pɔ̈rɔ̈-yângâ", "pjcrjc-yJangJa", "pCrC-YANGA"},
	{"pɔtɔ", "pctc", "pctc"},
	{"pɔtɔpɔ̂tɔ", "pctcpJctc", "pctcPCtc"},
	{"pulûsu", "pulJusu", "puLUsu"},
	{"pupu", "pupu", "pupu"},
	{"pupu", "pupu", "pupu"},
	{"pûpûlɛngɛ", "pJupJulxngx", "PUPUlxngx"},
	{"pûpûlɛngɛ", "pJupJulxngx", "PUPUlxngx"},
	{"pupu-sêse", "pupu-sJese", "pupu-SEse"},
	{"purû", "purJu", "puRU"},
	{"purû tî ngû", "purJu tJi ngJu", "puRU TI NGU"},
	{"pûsu", "pJusu", "PUsu"},
	{"pûsu-pûsu", "pJusu-pJusu", "PUsu-PUsu"},
	{"pûsu-pûsu", "pJusu-pJusu", "PUsu-PUsu"},
	{"sâa", "sJaa", "SAa"},
	{"sâa", "sJaa", "SAa"},
	{"sâa-kilöo", "sJaa-kiljoo", "SAa-kilOo"},
	{"sâa-ngonga", "sJaa-ngonga", "SAa-ngonga"},
	{"sâa pendä", "sJaa pendja", "SAa pendA"},
	{"sâa-pɛ̈tɛ̈", "sJaa-pjxtjx", "SAa-pXtX"},
	{"sâa to", "sJaa to", "SAa to"},
	{"sâa-wâ", "sJaa-wJa", "SAa-WA"},
	{"saba", "saba", "saba"},
	{"sägbä", "sjagbja", "sAgbA"},
	{"sâi", "sJai", "SAi"},
	{"sâki", "sJaki", "SAki"},
	{"sâki", "sJaki", "SAki"},
	{"sâki-", "sJaki-", "SAki-"},
	{"sakpä", "sakpja", "sakpA"},
	{"sâla", "sJala", "SAla"},
	{"sâla", "sJala", "SAla"},
	{"saläada", "saljaada", "salAada"},
	{"sâla na", "sJala na", "SAla na"},
	{"sâla na bɛ̂ ɔ̂kɔ", "sJala na bJx Jckc", "SAla na BX Ckc"},
	{"sâla na bɛ̂ ûse", "sJala na bJx Juse", "SAla na BX Use"},
	{"sâla yângâ", "sJala yJangJa", "SAla YANGA"},
	{"sambâ", "sambJa", "saMBA"},
	{"sâmba", "sJamba", "SAmba"},
	{"sâmba tî bengbä", "sJamba tJi bengbja", "SAmba TI bengbA"},
	{"sâmba tî vurü", "sJamba tJi vurju", "SAmba TI vurU"},
	{"sambêla", "sambJela", "saMBEla"},
	{"sambêla", "sambJela", "saMBEla"},
	{"sândâga", "sJandJaga", "SANDAga"},
	{"sandûgu", "sandJugu", "saNDUgu"},
	{"sangbi", "sangbi", "sangbi"},
	{"sangbi", "sangbi", "sangbi"},
	{"sangbi-lêgë", "sangbi-lJegje", "sangbi-LEgE"},
	{"sangbi-wâ", "sangbi-wJa", "sangbi-WA"},
	{"sängï", "sjangji", "sAngI"},
	{"sängï bulɛ̂ɛ", "sjangji bulJxx", "sAngI buLXx"},
	{"sängï fɔndɔ", "sjangji fcndc", "sAngI fcndc"},
	{"sango", "sango", "sango"},
	{"sängɔ̈", "sjangjc", "sAngC"},
	{"sântînî", "sJantJinJi", "SANTINI"},
	{"sanze", "sanze", "sanze"},
	{"sânzîrî", "sJanzJirJi", "SANZIRI"},
	{"särä", "sjarja", "sArA"},
	{"sarawîsi", "sarawJisi", "saraWIsi"},
	{"sasa", "sasa", "sasa"},
	{"sasa", "sasa", "sasa"},
	{"sê", "sJe", "SE"},
	{"sɛ̂-", "sJx-", "SX-"},
	{"seko", "seko", "seko"},
	{"selêka", "selJeka", "seLEka"},
	{"sɛmbɛ̈", "sxmbjx", "sxmbX"},
	{"sɛ̂ndâ", "sJxndJa", "SXNDA"},
	{"sɛ̂ndâ-", "sJxndJa-", "SXNDA-"},
	{"sɛ̈ndɛ̈", "sjxndjx", "sXndX"},
	{"sɛ̈nɛ̈", "sjxnjx", "sXnX"},
	{"sɛ̂ngɛ̂", "sJxngJx", "SXNGX"},
	{"sɛ̂ngɛ̂", "sJxngJx", "SXNGX"},
	{"sɛpɛ̈", "sxpjx", "sxpX"},
	{"sɛpɛla", "sxpxla", "sxpxla"},
	{"sɛpɛla", "sxpxla", "sxpxla"},
	{"sɛ̈pɛ̈längɔ̈-zo", "sjxpjxljangjc-zo", "sXpXlAngC-zo"},
	{"serê", "serJe", "seRE"},
	{"sêse", "sJese", "SEse"},
	{"sesêe", "sesJee", "seSEe"},
	{"sêtâ", "sJetJa", "SETA"},
	{"sɛ̈tɛ̈", "sjxtjx", "sXtX"},
	{"sɛ̈ tî kä", "sjx tJi kja", "sX TI kA"},
	{"sêwâ", "sJewJa", "SEWA"},
	{"sî", "sJi", "SI"},
	{"sï", "sji", "sI"},
	{"sï", "sji", "sI"},
	{"sï", "sji", "sI"},
	{"sï", "sji", "sI"},
	{"sïgî", "sjigJi", "sIGI"},
	{"sîgïgî", "sJigjigJi", "SIgIGI"},
	{"simba", "simba", "simba"},
	{"simbä", "simbja", "simbA"},
	{"simîsi", "simJisi", "siMIsi"},
	{"sî na", "sJi na", "SI na"},
	{"sindi", "sindi", "sindi"},
	{"sînga", "sJinga", "SInga"},
	{"sîngâ", "sJingJa", "SINGA"},
	{"singi", "singi", "singi"},
	{"singîla", "singJila", "siNGIla"},
	{"singîla", "singJila", "siNGIla"},
	{"singîla", "singJila", "siNGIla"},
	{"sïngɔ̈", "sjingjc", "sIngC"},
	{"sïngɔ̈-lâ", "sjingjc-lJa", "sIngC-LA"},
	{"sïɔ̈-", "sjijc-", "sIjC-"},
	{"sïɔ̈-bä", "sjijc-bja", "sIjC-bA"},
	{"sïɔ̈-dëbä", "sjijc-djebja", "sIjC-dEbA"},
	{"sïɔ̈-kpälë", "sjijc-kpjalje", "sIjC-kpAlE"},
	{"sïɔ̈-kpärï", "sjijc-kpjarji", "sIjC-kpArI"},
	{"sïɔ̈nî", "sjijcnJi", "sIjCNI"},
	{"sïɔ̈nî", "sjijcnJi", "sIjCNI"},
	{"sïɔ̈nî", "sjijcnJi", "sIjCNI"},
	{"sïɔ̈nî pêrë", "sjijcnJi pJerje", "sIjCNI PErE"},
	{"sïɔ̈-yê", "sjijc-yJe", "sIjC-YE"},
	{"sïɔ̈-zo", "sjijc-zo", "sIjC-zo"},
	{"siri", "siri", "siri"},
	{"sîrîrî", "sJirJirJi", "SIRIRI"},
	{"sîrîrî", "sJirJirJi", "SIRIRI"},
	{"sisa", "sisa", "sisa"},
	{"sisi", "sisi", "sisi"},
	{"sï-zuka", "sji-zuka", "sI-zuka"},
	{"so", "so", "so"},
	{"sô", "sJo", "SO"},
	{"sô", "sJo", "SO"},
	{"sô", "sJo", "SO"},
	{"sô", "sJo", "SO"},
	{"sô", "sJo", "SO"},
	{"sô", "sJo", "SO"},
	{"sɔ̂", "sJc", "SC"},
	{"sɔ̂ bɛnda", "sJc bxnda", "SC bxnda"},
	{"sombêe", "sombJee", "soMBEe"},
	{"sombere", "sombere", "sombere"},
	{"sô mo yê", "sJo mo yJe", "SO mo YE"},
	{"sô mvɛnî sï", "sJo mvxnJi sji", "SO mvxNI sI"},
	{"sôn", "sJon", "SON"},
	{"sôn", "sJon", "SON"},
	{"söngö", "sjongjo", "sOngO"},
	{"söngö", "sjongjo", "sOngO"},
	{"sɔngɔ̈", "scngjc", "scngC"},
	{"sɔngɔ̈-bɛ̂", "scngjc-bJx", "scngC-BX"},
	{"songosongo", "songosongo", "songosongo"},
	{"soro", "soro", "soro"},
	{"sorö", "sorjo", "sorO"},
	{"sɔ̈rɔ̈", "sjcrjc", "sCrC"},
	{"soronga", "soronga", "soronga"},
	{"sösö", "sjosjo", "sOsO"},
	{"sɔsɔ", "scsc", "scsc"},
	{"su", "su", "su"},
	{"su", "su", "su"},
	{"sû", "sJu", "SU"},
	{"sua", "sua", "sua"},
	{"sua", "sua", "sua"},
	{"sûâ", "sJuJa", "SUA"},
	{"sûî-", "sJuJi-", "SUI-"},
	{"suïya", "sujiya", "sujIya"},
	{"sukâni", "sukJani", "suKAni"},
	{"sûku", "sJuku", "SUku"},
	{"sûku", "sJuku", "SUku"},
	{"sukûla", "sukJula", "suKUla"},
	{"sukûla bɛ̂", "sukJula bJx", "suKUla BX"},
	{"sükülängɔ̈ ngû", "sjukjuljangjc ngJu", "sUkUlAngC NGU"},
	{"sukûla ngû", "sukJula ngJu", "suKUla NGU"},
	{"sukûlu", "sukJulu", "suKUlu"},
	{"sulëe", "suljee", "sulEe"},
	{"suma", "suma", "suma"},
	{"sümä", "sjumja", "sUmA"},
	{"suma süma", "suma sjuma", "suma sUma"},
	{"sû-mbɛ̈tï", "sJu-mbjxtji", "SU-mbXtI"},
	{"sumbu", "sumbu", "sumbu"},
	{"sungba", "sungba", "sungba"},
	{"sungbä", "sungbja", "sungbA"},
	{"süngbängɔ̈", "sjungbjangjc", "sUngbAngC"},
	{"süngɔ̈-mbɛ̈tï", "sjungjc-mbjxtji", "sUngC-mbXtI"},
	{"sûpu", "sJupu", "SUpu"},
	{"sura", "sura", "sura"},
	{"surä", "surja", "surA"},
	{"sûru", "sJuru", "SUru"},
	{"sûru", "sJuru", "SUru"},
	{"susu", "susu", "susu"},
	{"ta", "ta", "ta"},
	{"tä-", "tja-", "tA-"},
	{"taä", "taja", "tajA"},
	{"taä-pandë", "taja-pandje", "tajA-pandE"},
	{"taä-sängɔ̈", "taja-sjangjc", "tajA-sAngC"},
	{"taä-tɛnɛ", "taja-txnx", "tajA-txnx"},
	{"taba", "taba", "taba"},
	{"tâgba", "tJagba", "TAgba"},
	{"tâkâ-", "tJakJa-", "TAKA-"},
	{"ta-kâsa", "ta-kJasa", "ta-KAsa"},
	{"tâ-li-tï", "tJa-li-tji", "TA-li-tI"},
	{"tambûla", "tambJula", "taMBUla"},
	{"tambûla", "tambJula", "taMBUla"},
	{"tambûla", "tambJula", "taMBUla"},
	{"tanga", "tanga", "tanga"},
	{"tangbi", "tangbi", "tangbi"},
	{"tangbi", "tangbi", "tangbi"},
	{"tâ-ngbɔ̈", "tJa-ngbjc", "TA-ngbC"},
	{"tä-ngbɔ̈", "tja-ngbjc", "tA-ngbC"},
	{"tangë", "tangje", "tangE"},
	{"tângo", "tJango", "TAngo"},
	{"ta-ngû", "ta-ngJu", "ta-NGU"},
	{"täpärë", "tjapjarje", "tApArE"},
	{"tara", "tara", "tara"},
	{"tara", "tara", "tara"},
	{"tarä", "tarja", "tarA"},
	{"ta-sêse", "ta-sJese", "ta-SEse"},
	{"tatalîta", "tatalJita", "tataLIta"},
	{"tatärä", "tatjarja", "tatArA"},
	{"tatärä-lɛ̂", "tatjarja-lJx", "tatArA-LX"},
	{"tatara ndo", "tatara ndo", "tatara ndo"},
	{"taza", "taza", "taza"},
	{"tɛ", "tx", "tx"},
	{"tɛ-kîri", "tx-kJiri", "tx-KIri"},
	{"tɛ-lötï", "tx-ljotji", "tx-lOtI"},
	{"tembe", "tembe", "tembe"},
	{"tende", "tende", "tende"},
	{"tɛnɛ", "txnx", "txnx"},
	{"tɛ̂nɛ̈", "tJxnjx", "TXnX"},
	{"tɛ̈nɛ̈", "tjxnjx", "tXnX"},
	{"tɛnɛ mvɛnɛ", "txnx mvxnx", "txnx mvxnx"},
	{"tɛ̈nɛ̈ngɔ̈ tɛ̈nɛ̈", "tjxnjxngjc tjxnjx", "tXnXngC tXnX"},
	{"tɛnɛ taä-tɛ̈nɛ̈", "txnx taja-tjxnjx", "txnx tajA-tXnX"},
	{"tɛnɛ tɛ̈nɛ̈", "txnx tjxnjx", "txnx tXnX"},
	{"tɛ̈nɛ̈ tî", "tjxnjx tJi", "tXnX TI"},
	{"tɛ̈nɛ̈ tî nyɛ", "tjxnjx tJi nyx", "tXnX TI nyx"},
	{"tɛ̈nɛ̈ tî nzapä", "tjxnjx tJi nzapja", "tXnX TI nzapA"},
	{"tɛ̈nɛ̈ tî sô", "tjxnjx tJi sJo", "tXnX TI SO"},
	{"tɛ̈nɛ̈ tî sô", "tjxnjx tJi sJo", "tXnX TI SO"},
	{"tɛ̂nga", "tJxnga", "TXnga"},
	{"tɛ̂nga-wâ", "tJxnga-wJa", "TXnga-WA"},
	{"tɛ̂ngbi", "tJxngbi", "TXngbi"},
	{"tɛ̂ngbi", "tJxngbi", "TXngbi"},
	{"tɛrɛ", "txrx", "txrx"},
	{"tɛrɛ", "txrx", "txrx"},
	{"tɛrɛ̂", "txrJx", "txRX"},
	{"tɛrɛ̂", "txrJx", "txRX"},
	{"tɛrɛ̂", "txrJx", "txRX"},
	{"tî", "tJi", "TI"},
	{"tï", "tji", "tI"},
	{"tï", "tji", "tI"},
	{"tï", "tji", "tI"},
	{"tîa", "tJia", "TIa"},
	{"tîâa", "tJiJaa", "TIAa"},
	{"tikî", "tikJi", "tiKI"},
	{"tikîsa", "tikJisa", "tiKIsa"},
	{"tîkɔ", "tJikc", "TIkc"},
	{"tîkɔ̈", "tJikjc", "TIkC"},
	{"tî-ndâ-nî", "tJi-ndJa-nJi", "TI-NDA-NI"},
	{"tipôi", "tipJoi", "tiPOi"},
	{"tiri", "tiri", "tiri"},
	{"tirika", "tirika", "tirika"},
	{"tîrîngbi", "tJirJingbi", "TIRIngbi"},
	{"tisa", "tisa", "tisa"},
	{"tisä", "tisja", "tisA"},
	{"tî-tɛnɛ", "tJi-txnx", "TI-txnx"},
	{"to", "to", "to"},
	{"tö", "tjo", "tO"},
	{"tö-", "tjo-", "tO-"},
	{"tɔ̈", "tjc", "tC"},
	{"tö-buä", "tjo-buja", "tO-bujA"},
	{"to-kua", "to-kua", "to-kua"},
	{"tokua", "tokua", "tokua"},
	{"toli", "toli", "toli"},
	{"tolï", "tolji", "tolI"},
	{"tö-li-tï", "tjo-li-tji", "tO-li-tI"},
	{"tôlo", "tJolo", "TOlo"},
	{"tomâti", "tomJati", "toMAti"},
	{"tombôka", "tombJoka", "toMBOka"},
	{"töndâ", "tjondJa", "tONDA"},
	{"töndö", "tjondjo", "tOndO"},
	{"tɔndɔ", "tcndc", "tcndc"},
	{"tɔ̈ndɔ̈ngɔ̈", "tjcndjcngjc", "tCndCngC"},
	{"tonga", "tonga", "tonga"},
	{"töngana", "tjongana", "tOngana"},
	{"töngana", "tjongana", "tOngana"},
	{"töngana nyɛ", "tjongana nyx", "tOngana nyx"},
	{"töngana tî sô", "tjongana tJi sJo", "tOngana TI SO"},
	{"töngasô", "tjongasJo", "tOngaSO"},
	{"töngasô", "tjongasJo", "tOngaSO"},
	{"tôngbi", "tJongbi", "TOngbi"},
	{"tôngbï", "tJongbji", "TOngbI"},
	{"tô-ngbɔ̈", "tJo-ngbjc", "TO-ngbC"},
	{"tongo", "tongo", "tongo"},
	{"töngɔ̈", "tjongjc", "tOngC"},
	{"tɔ̈ngɔ̈", "tjcngjc", "tCngC"},
	{"tongolo", "tongolo", "tongolo"},
	{"tongoro", "tongoro", "tongoro"},
	{"tɔnɔ", "tcnc", "tcnc"},
	{"tɔ̂ɔ", "tJcc", "TCc"},
	{"tɔrɔ̂rɔ̂", "tcrJcrJc", "tcRCRC"},
	{"toto", "toto", "toto"},
	{"toto", "toto", "toto"},
	{"tɔtɔ", "tctc", "tctc"},
	{"tukîa", "tukJia", "tuKIa"},
	{"tukîa", "tukJia", "tuKIa"},
	{"tûku", "tJuku", "TUku"},
	{"tûku", "tJuku", "TUku"},
	{"tûku", "tJuku", "TUku"},
	{"tûku môlɛngɛ̂", "tJuku mJolxngJx", "TUku MOlxNGX"},
	{"tumba", "tumba", "tumba"},
	{"tumba", "tumba", "tumba"},
	{"tungu", "tungu", "tungu"},
	{"turu", "turu", "turu"},
	{"turûgu", "turJugu", "tuRUgu"},
	{"tûrûngu", "tJurJungu", "TURUngu"},
	{"tutü", "tutju", "tutU"},
	{"uru", "uru", "uru"},
	{"uru", "uru", "uru"},
	{"ûru", "Juru", "Uru"},
	{"ûrûlû", "JurJulJu", "URULU"},
	{"ûse", "Juse", "Use"},
	{"ûse", "Juse", "Use"},
	{"usïö", "usjijo", "usIjO"},
	{"usïö", "usjijo", "usIjO"},
	{"va", "va", "va"},
	{"vaka", "vaka", "vaka"},
	{"vârä", "vJarja", "VArA"},
	{"vâtândâ", "vJatJandJa", "VATANDA"},
	{"vɛkɛ̈", "vxkjx", "vxkX"},
	{"vîi", "vJii", "VIi"},
	{"vo", "vo", "vo"},
	{"vɔ", "vc", "vc"},
	{"vongbâ", "vongbJa", "voNGBA"},
	{"vɔ ngêrë", "vc ngJerje", "vc NGErE"},
	{"vɔ̈ngɔ̈", "vjcngjc", "vCngC"},
	{"vɔrɔ", "vcrc", "vcrc"},
	{"vɔ̈rɔ̈ngɔ̈", "vjcrjcngjc", "vCrCngC"},
	{"vɔrɔ tɛrɛ̂", "vcrc txrJx", "vcrc txRX"},
	{"vɔ to ", "vc to ", "vc to "},
	{"vɔ vɔ̈ngɔ̈ ", "vc vjcngjc ", "vc vCngC "},
	{"vɔvɔrɔ", "vcvcrc", "vcvcrc"},
	{"vü", "vju", "vU"},
	{"vü", "vju", "vU"},
	{"vünga", "vjunga", "vUnga"},
	{"vukɔ̈", "vukjc", "vukC"},
	{"vûkɔ̈", "vJukjc", "VUkC"},
	{"vukɔ̈-kɛ̂tɛ̂", "vukjc-kJxtJx", "vukC-KXTX"},
	{"vûkɔ̈ kɛ̂tɛ̂", "vJukjc kJxtJx", "VUkC KXTX"},
	{"vûkɔ-lɛ̈", "vJukc-ljx", "VUkc-lX"},
	{"vukɔ̈ mbunzû", "vukjc mbunzJu", "vukC mbuNZU"},
	{"vûkɔ̈ mîngi", "vJukjc mJingi", "VUkC MIngi"},
	{"vukɔ̈-vukɔ̈", "vukjc-vukjc", "vukC-vukC"},
	{"vümä", "vjumja", "vUmA"},
	{"vundû", "vundJu", "vuNDU"},
	{"vuru", "vuru", "vuru"},
	{"vurü", "vurju", "vurU"},
	{"vurü", "vurju", "vurU"},
	{"vuru kɛ̂tɛ̂", "vuru kJxtJx", "vuru KXTX"},
	{"vurü-kɛ̂tɛ̂", "vurju-kJxtJx", "vurU-KXTX"},
	{"vuru mîngi", "vuru mJingi", "vuru MIngi"},
	{"vurü-vurü", "vurju-vurju", "vurU-vurU"},
	{"wa", "wa", "wa"},
	{"wa", "wa", "wa"},
	{"wa", "wa", "wa"},
	{"wa-", "wa-", "wa-"},
	{"wâ", "wJa", "WA"},
	{"waäwa", "wajawa", "wajAwa"},
	{"waäwa", "wajawa", "wajAwa"},
	{"wa-bɛ̂", "wa-bJx", "wa-BX"},
	{"wa-bindi", "wa-bindi", "wa-bindi"},
	{"wa-fängɔ̈-kua", "wa-fjangjc-kua", "wa-fAngC-kua"},
	{"wa-fängɔ̈-mbɛ̈tï", "wa-fjangjc-mbjxtji", "wa-fAngC-mbXtI"},
	{"wa-fängɔ̈-yê", "wa-fjangjc-yJe", "wa-fAngC-YE"},
	{"wa-hânda", "wa-hJanda", "wa-HAnda"},
	{"wala", "wala", "wala"},
	{"wâlï", "wJalji", "WAlI"},
	{"wâlï", "wJalji", "WAlI"},
	{"wâlï", "wJalji", "WAlI"},
	{"wâlï-", "wJalji-", "WAlI-"},
	{"wâlï-kɔ̂lï", "wJalji-kJclji", "WAlI-KClI"},
	{"wâlï-wâlï", "wJalji-wJalji", "WAlI-WAlI"},
	{"wa-mä-bɛ̂", "wa-mja-bJx", "wa-mA-BX"},
	{"wa-mändängɔ̈-kua", "wa-mjandjangjc-kua", "wa-mAndAngC-kua"},
	{"wa-mändängɔ̈-mbɛ̈tï", "wa-mjandjangjc-mbjxtji", "wa-mAndAngC-mbXtI"},
	{"wa-mändängɔ̈-yê", "wa-mjandjangjc-yJe", "wa-mAndAngC-YE"},
	{"wa-ndê", "wa-ndJe", "wa-NDE"},
	{"wängɔ̈", "wjangjc", "wAngC"},
	{"wängɔ̈-bɛ̂", "wjangjc-bJx", "wAngC-BX"},
	{"wa-nzï", "wa-nzji", "wa-nzI"},
	{"wa-polîsi", "wa-polJisi", "wa-poLIsi"},
	{"wa-pulûsu", "wa-pulJusu", "wa-puLUsu"},
	{"wara", "wara", "wara"},
	{"wa-sɛ̂ndâ", "wa-sJxndJa", "wa-SXNDA"},
	{"wa-süngɔ̈-mbɛ̈tï", "wa-sjungjc-mbjxtji", "wa-sUngC-mbXtI"},
	{"wätäkä", "wjatjakja", "wAtAkA"},
	{"wa-tokua", "wa-tokua", "wa-tokua"},
	{"wa-turu", "wa-turu", "wa-turu"},
	{"wa-yângâ-nzapä", "wa-yJangJa-nzapja", "wa-YANGA-nzapA"},
	{"wa-zibä", "wa-zibja", "wa-zibA"},
	{"wên", "wJen", "WEN"},
	{"wërë", "wjerje", "wErE"},
	{"wɛ̂rɛ", "wJxrx", "WXrx"},
	{"wɛ̈rɛ̈ngɔ̈", "wjxrjxngjc", "wXrXngC"},
	{"wɛ̈rɛ̈ngɔ̈", "wjxrjxngjc", "wXrXngC"},
	{"wö", "wjo", "wO"},
	{"wɔ", "wc", "wc"},
	{"wɔ bɛ̂", "wc bJx", "wc BX"},
	{"woga", "woga", "woga"},
	{"wögarâ", "wjogarJa", "wOgaRA"},
	{"wôko", "wJoko", "WOko"},
	{"wököngɔ̈", "wjokjongjc", "wOkOngC"},
	{"wömba", "wjomba", "wOmba"},
	{"wömba", "wjomba", "wOmba"},
	{"wɔ̈rɔ̈", "wjcrjc", "wCrC"},
	{"wɔ tɛrɛ̂", "wc txrJx", "wc txRX"},
	{"wɔ̂tɔrɔ", "wJctcrc", "WCtcrc"},
	{"woza", "woza", "woza"},
	{"wü", "wju", "wU"},
	{"wûku", "wJuku", "WUku"},
	{"wüngɔ̈", "wjungjc", "wUngC"},
	{"wüngɔ̈", "wjungjc", "wUngC"},
	{"wûrûwûrû", "wJurJuwJurJu", "WURUWURU"},
	{"wûsûwusu", "wJusJuwusu", "WUSUwusu"},
	{"wûyâwuya", "wJuyJawuya", "WUYAwuya"},
	{"ya", "ya", "ya"},
	{"yâ", "yJa", "YA"},
	{"yâ", "yJa", "YA"},
	{"yäkä", "yjakja", "yAkA"},
	{"yakepaka", "yakepaka", "yakepaka"},
	{"yakɛ̂rɛ̂-", "yakJxrJx-", "yaKXRX-"},
	{"yakɛ̂rɛ̂-ngonga", "yakJxrJx-ngonga", "yaKXRX-ngonga"},
	{"yändä", "yjandja", "yAndA"},
	{"yângâ", "yJangJa", "YANGA"},
	{"yângâ-da", "yJangJa-da", "YANGA-da"},
	{"yangba", "yangba", "yangba"},
	{"yangö", "yangjo", "yangO"},
	{"yapakara", "yapakara", "yapakara"},
	{"yapü", "yapju", "yapU"},
	{"yapü", "yapju", "yapU"},
	{"yâpu", "yJapu", "YApu"},
	{"yäsï", "yjasji", "yAsI"},
	{"yaya", "yaya", "yaya"},
	{"yäyû", "yjayJu", "yAYU"},
	{"yazo", "yazo", "yazo"},
	{"yê", "yJe", "YE"},
	{"yê", "yJe", "YE"},
	{"yɛ", "yx", "yx"},
	{"yê-daä", "yJe-daja", "YE-dajA"},
	{"yɛkɛ", "yxkx", "yxkx"},
	{"yɛkɛ", "yxkx", "yxkx"},
	{"yɛkɛ na", "yxkx na", "yxkx na"},
	{"yɛkɛ tî", "yxkx tJi", "yxkx TI"},
	{"yɛkɛ-yɛkɛ", "yxkx-yxkx", "yxkx-yxkx"},
	{"yêkpâ", "yJekpJa", "YEKPA"},
	{"yême", "yJeme", "YEme"},
	{"yenga", "yenga", "yenga"},
	{"yêngbi", "yJengbi", "YEngbi"},
	{"yênge", "yJenge", "YEnge"},
	{"yëngëngɔ̈-sêse", "yjengjengjc-sJese", "yEngEngC-SEse"},
	{"yɛngɛrɛ", "yxngxrx", "yxngxrx"},
	{"yɛ̈ngɛ̈rɛ̈", "yjxngjxrjx", "yXngXrX"},
	{"yëngɔ̈-daä", "yjengjc-daja", "yEngC-dajA"},
	{"yëngɔ̈-ndö", "yjengjc-ndjo", "yEngC-ndO"},
	{"yëngɔ̈-ndö", "yjengjc-ndjo", "yEngC-ndO"},
	{"yɛ̈rɛ̈", "yjxrjx", "yXrX"},
	{"yîkɔ", "yJikc", "YIkc"},
	{"yingɔ̈", "yingjc", "yingC"},
	{"yingɔ̈", "yingjc", "yingC"},
	{"yingɔ̈-gbïä", "yingjc-gbjija", "yingC-gbIjA"},
	{"yingɔ̈-va", "yingjc-va", "yingC-va"},
	{"yingɔ̈-vurü", "yingjc-vurju", "yingC-vurU"},
	{"yɔ", "yc", "yc"},
	{"yɔ̂", "yJc", "YC"},
	{"yɔ̈mbɔ̈", "yjcmbjc", "yCmbC"},
	{"yongba", "yongba", "yongba"},
	{"yɔngɔ̂rɔ", "ycngJcrc", "ycNGCrc"},
	{"yɔrɔ̈", "ycrjc", "ycrC"},
	{"yɔ̂rɔ", "yJcrc", "YCrc"},
	{"yɔ̈rɔ̈ngɔ̈", "yjcrjcngjc", "yCrCngC"},
	{"yɔ̈rɔ̈ngɔ̈", "yjcrjcngjc", "yCrCngC"},
	{"yü", "yju", "yU"},
	{"yuru", "yuru", "yuru"},
	{"yûru", "yJuru", "YUru"},
	{"zä", "zja", "zA"},
	{"zä", "zja", "zA"},
	{"zâbolo", "zJabolo", "ZAbolo"},
	{"zâkâri", "zJakJari", "ZAKAri"},
	{"zakarima", "zakarima", "zakarima"},
	{"zâkâzaka", "zJakJazaka", "ZAKAzaka"},
	{"zalamäa", "zalamjaa", "zalamAa"},
	{"zambala", "zambala", "zambala"},
	{"zängɔ̈", "zjangjc", "zAngC"},
	{"zaza", "zaza", "zaza"},
	{"zɛ", "zx", "zx"},
	{"zêe", "zJee", "ZEe"},
	{"zɛgbɛ-", "zxgbx-", "zxgbx-"},
	{"zɛgbɛ-ngonga", "zxgbx-ngonga", "zxgbx-ngonga"},
	{"zegë", "zegje", "zegE"},
	{"zɛmbɛ", "zxmbx", "zxmbx"},
	{"zɛmɛ", "zxmx", "zxmx"},
	{"zën", "zjen", "zEN"},
	{"zën", "zjen", "zEN"},
	{"zëngɔ̈ ndo", "zjengjc ndo", "zEngC ndo"},
	{"zî", "zJi", "ZI"},
	{"zï", "zji", "zI"},
	{"zîâ", "zJiJa", "ZIA"},
	{"zîâ bɛ̂", "zJiJa bJx", "ZIA BX"},
	{"zîâ-bɛ̂", "zJiJa-bJx", "ZIA-BX"},
	{"zîâ kɔ̂lï", "zJiJa kJclji", "ZIA KClI"},
	{"zîâ lêgë na", "zJiJa lJegje na", "ZIA LEgE na"},
	{"zîâ na bɛ̂", "zJiJa na bJx", "ZIA na BX"},
	{"zîâ na ndö", "zJiJa na ndjo", "ZIA na ndO"},
	{"zîâ ngîâ na bɛ̂ tî", "zJiJa ngJiJa na bJx tJi", "ZIA NGIA na BX TI"},
	{"zïängɔ̈", "zjijangjc", "zIjAngC"},
	{"zîâ ngû", "zJiJa ngJu", "ZIA NGU"},
	{"zîâ wâlï", "zJiJa wJalji", "ZIA WAlI"},
	{"zîâ yângâ", "zJiJa yJangJa", "ZIA YANGA"},
	{"zibä", "zibja", "zibA"},
	{"zî bɔngɔ̈", "zJi bcngjc", "ZI bcngC"},
	{"zî-bɔngɔ̈", "zJi-bcngjc", "ZI-bcngC"},
	{"zîdɔrɔ", "zJidcrc", "ZIdcrc"},
	{"zigidâ", "zigidJa", "zigiDA"},
	{"zîngɔ", "zJingc", "ZIngc"},
	{"zîngɔ na", "zJingc na", "ZIngc na"},
	{"zo", "zo", "zo"},
	{"zɔ̈", "zjc", "zC"},
	{"zo kûɛ̂ zo", "zo kJuJx zo", "zo KUX zo"},
	{"zonga", "zonga", "zonga"},
	{"zonga", "zonga", "zonga"},
	{"zöngö", "zjongjo", "zOngO"},
	{"zɔ̈ngɔ̈", "zjcngjc", "zCngC"},
	{"zo tî nzï", "zo tJi nzji", "zo TI nzI"},
	{"zo wa", "zo wa", "zo wa"},
	{"zɔ̈ wâ", "zjc wJa", "zC WA"},
	{"zûu", "zJuu", "ZUu"},
	{"zûu", "zJuu", "ZUu"},
	{"zûâ", "zJuJa", "ZUA"},
	{"züngɔ̈", "zjungjc", "zUngC"},
}
