package main

import (
	"fmt"
	"strings"

	lex "github.com/zokwezo/sango/src/lib/lexicon"
	sse "github.com/zokwezo/sango/src/lib/sse"
)

func main() {
	posCount := make(map[string]int)
	categoryCount := make(map[string]int)
	frequencyCount := make(map[int]int)
	for k, r := range lex.LexiconRows() {
		a := strings.ToLower(r.Toneless)
		b := strings.ToLower(r.Heightless)
		c := strings.ToLower(r.Lemma)
		d := r.Canonical
		e := strings.ToUpper(r.UDPos)
		f := r.UDFeature
		g := strings.ToUpper(r.Category)
		h := r.Frequency
		i := r.EnglishTranslation
		j := r.EnglishDefinition
		posCount[e]++
		categoryCount[g]++
		frequencyCount[h]++

		// Flag lexicon entries with bad Canonical
		sses, err := sse.CanonicalToSSEs(d)
		if err != nil {
			fmt.Printf("unexpected error returned from CanonicalToSSEs[%v]\nerr = %v", d, err)
			panic("bad Canonical")
		}
		// Verify that the Toneless, Heightless, and Lemma columns are exactly generated by the Canonical column.
		word := sse.SSE(0x0)
		if k == 0 && a == "" {
		} else if len(sses) == 1 {
			word = sses[0]
		} else {
			panic("bad len(sses)")
		}
		{
			var sd strings.Builder
			word.WriteAsTonelessTo(&sd)
			if a != sd.String() {
				panic("bad Toneless")
			}
		}
		{
			var sd strings.Builder
			word.WriteAsHeightlessTo(&sd)
			if b != sd.String() {
				panic("bad Heightless")
			}
		}
		{
			var sd strings.Builder
			word.WriteAsLemmaTo(&sd)
			if c != sd.String() {
				panic("bad Lemma")
			}
		}
		{
			var sd strings.Builder
			word.WriteAsCanonicalTo(&sd)
			if d != sd.String() {
				panic("bad Canonical")
			}
		}
		w := uint64(word)
		if w != 0 && w&0xF_000_000_000_000_000 != 0x8_000_000_000_000_000 {
			fmt.Printf("Unexpected 4 MSB: word = %016X\n", w)
			panic("Bad word")
		}
		u := sse.UnpadRight(w)
		fmt.Printf("%016X\t\t{0x%X, %q, %q, %q, %v, %q, %q},\n", w, u, e, f, g, h, i, j)
		u = sse.PadRight(w)
		if u != w {
			fmt.Printf("w = 0x%016X\n   u = 0x%016X\n", w, u)
			panic("bad word from u")
		}
	}
	fmt.Println("")
	fmt.Println("POS")
	posTotal := 0
	for _, count := range posCount {
		posTotal += count
	}
	for pos, count := range posCount {
		fmt.Printf("%s\t%v\t%v\n", pos, count, (200*count+posTotal)/(posTotal*2))
	}
	fmt.Println("")
	fmt.Println("CATEGORY")
	categoryTotal := 0
	for _, count := range categoryCount {
		categoryTotal += count
	}
	for category, count := range categoryCount {
		fmt.Printf("%s\t%v\t%v\n", category, count, (200*count+categoryTotal)/(categoryTotal*2))
	}
	fmt.Println("")
	fmt.Println("FREQUENCY")
	frequencyTotal := 0
	for _, count := range frequencyCount {
		frequencyTotal += count
	}
	for frequency, count := range frequencyCount {
		fmt.Printf("%v\t%v\t%v\n", frequency, count, (200*count+frequencyTotal)/(frequencyTotal*2))
	}
}
